<b><center>
<span style="font-size: 24pt; line-height: 1.2">
COMS W4111: Introduction to Databases
</span>
</center></b>
<p>
<i><center>
<span style="font-size: 20pt; line-height: 1.2">
Lecture 3: Relational Model Details<br>(V 1.0)
</span>
</center></i>

__Environment Set Up__

In [1]:
%load_ext sql
%sql mysql+pymysql://root:dbuserdbuser@localhost/lahman2019raw
%sql select * from people where playerid='willite01'

2 rows affected.


[('willite01', '1918', '8', '30', 'USA', 'CA', 'San Diego', '2002', '7', '5', 'USA', 'FL', 'Inverness', 'Ted', 'Williams', 'Theodore Samuel', '205', '75', 'L', 'R', '1939-04-20', '1960-09-28', 'willt103', 'willite01'),
 ('willite01', '1918', '8', '30', 'USA', 'CA', 'San Diego', '2002', '7', '5', 'USA', 'FL', 'Inverness', 'Ted', 'Williams', 'Theodore Samuel', '205', '75', 'L', 'R', '1939-04-20', '1960-09-28', 'willt103', 'willite01')]

# Introduction

## Questions?

## Today's Topics

1. Make up lecture.<br><br>
1. Modified course approach.
<br><br>
1. Conceptual application we could build using databases<br><br>
1. Database applications:
    - Introduction to concept.
    - Common types of database applications.
    - Web applications.
<br><br>
1. White board walk through of a web application. I did not get a chance to do slides after speaking with Aly and Ara.
    1. Web page.
    2. Templates, models, controllers, ...
    3. Application and application server.
    4. REST/Web APIs.
    5. Web 101:
        1. Catalog
        2. Shopping cart
        3. Inventory check
        4. Credit card check
        5. Submit and fulfillment.
<br><br>
1. SQL for initial use case: Finding information about people.
<br><br>
1. iPython Magics and connections.
<br><br>
1. SQL for another use case: INSERT
    - INSERT
    - Data cleanup
    - Integrity constraints
<br><br>
1. Relationships
<br><br>
1. More advanced SQL:
    - JOINs
    - Aggregations
<br><br>
1. REST APIs
<br><br>
1. HW 2

# Makeup Lecture

- I have seen from scheduling OH that we all have crazy schedules.


- Trying to pick a single, good time for the makeup lecture would be impossible.


- I will hold a couple of online, web lectures that I will also record.


- I will cover some of the topics in lectures that I have skipped, as well as some of the more straightforward material. This is material for which there is information in books and tutorials.
    - Relational Model (theory).
    - Some details of SQL.
    
    
- It is also likely that I will run out of time today, which means the weekend lecture would be the conclusion.


- I need to cover this material for HW2.
    
    
- I will start this weekend.

# Course Modifications

## Textbook

1. I stated in the first lecture that textbooks are out-of-date, and that online information is the best source.
<br><br>
1. This is still true. There are good online tutorials for most of the topics we will cover.
<br><br>
1. The CS department will be switching to a new book next semester, and I have reviewed it and think it is good.
    - _Database System Concepts 7th Edition_ by Abraham Silberschatz, Henry Korth, S. Sudarshan. ISBN-13: 978-0078022159.
    - The textbook is optional. I will switch to this textbook for embedded slides and __some__ examples.
    - We will continue to work with other database schema, e.g. Lahman2019, newly designed schema.
    
    
## Homework Assignments

1. My homework assignments teach important, practical concepts and build important skills.
<br><br>
1. It is time for me to accept, after 5 semesters, that the assignments are too hard.
<br><br>
1. I am going to have the TAs, scope, define and document the HW assignments.
    1. The TAs better understand the multiple constraints that students face.
    1. Most of them have gone through similar homeworks. They can identify the requirements/tasks that were educational and effective and the requirements/tasks that generated needless work, confusion, etc.
    1. I will define _commander's intent_ and review.<br><br>
1. The TAs will also enumerate concepts needed for the homework that I have to explicitly cover. There are things that are obvious to me, and it never occurs to me that it is not obvious to you.
<br><br>
1. We are working on the details.

# Sample Application

## Overview

__Some Terms__

- "Fantasy baseball is a game in which people manage rosters of league baseball players, either online or in a physical location, using fictional fantasy baseball team names. The participants compete against one another using those players' real life statistics to score points." (https://en.wikipedia.org/wiki/Fantasy_baseball)



- "Moneyball: The Art of Winning an Unfair Game is a book by Michael Lewis, published in 2003, about the Oakland Athletics baseball team and its general manager Billy Beane. Its focus is the team's analytical, evidence-based, sabermetric approach to assembling a competitive baseball team despite Oakland's small budget. A film based on the book, starring Brad Pitt and Jonah Hill, was released in 2011.<br><br>
The central premise of Moneyball is that the collective wisdom of baseball insiders (including players, managers, coaches, scouts, and the front office) over the past century is subjective and often flawed." (https://en.wikipedia.org/wiki/Moneyball)



__A software system supporting a fantasy baseball community might have the following functional area:__


- _BaseballInfo Data Microservice:_ Allows users to query and explore data about players and their performance. Data comes from modified Lahman2019 schema and data.


- _Fantasy Baseball Data Microservice:_ Allows users to create an account, define a fantasy team, define a fantasy league, assign players to teams, etc. The database is a newly designed database and data model.


- _Social Interaction Microservice:_ Allows users to follow, like, comment, etc. on teams, players, users, ...


- _Discussion/Comment Data Microservice:_ Stores comments, responses, discussion threads, etc.


- _Analytics/Machine Learning Data Microservice:_ A database of analyzed and processed baseball performance interface that enables analysis and prediction using machine learning.


- _Application Business/Logic Microservice:_ Implement business logic and rules, primarily governing correct operation of the fantasy league and rules.


- _Caching Microservice:_ REST API and data access response cache to optimize performance.


- _Static Content Web Server:_ Delivers HTML, CSS, images, JavaScript, etc. to web browser UI.


- _User Interface:_ Browser application using AngularJS.


| <img src="../../images/6156_project_structure.jpeg"> |
| :---: |
| __Tentative Project Architecture__ |

- This would be a huge amount of work for a large team over a period of time.


- But, it would demonstrate many of the core concepts and technologies in database solutions:


- We will touch on various database aspects of the scenario.

# Database Applications

## The Big Picture

<hr style="height:2px;">

| <img src="../../images/new_book_ch1_21.jpg" width="900px"> |
| :---: |
| __Database Applications__ |

<hr style="height:2px;">


- Some examples of application logic:
    - Complex computations using the data.
    - Coordinating integrity of data between multiple different databases and database models.
    - Complex input parameter verification.
    
    
## Types of Database Applications

- There are several (too many) ways to classify applications and scenarios that use databases. Some examples
 

- One classification approach:
    - _Real-time (online) systems,_ where you submit requests to do a small amount of work that has to be done before some very early deadline, or interactively why the user waits.
    - _Batch processing systems,_ where you submit a a bunch of files, a "job" containing multiple subprograms, and later receive output in the form of a file.
    - _Data warehouse systems,_ where reporting programs and ad hoc queries access data that is integrated from multiple data sources.
    

- Real-time (online) system:
    - Most familiar is interactive web applications, e.g. CourseWorks, online banking.
    - Other examples: ATMs, airline check-in kiosks and boarding pass readers, ...



| <img src="../../images/very-simple-web-app.jpg" width="900px"> |
| :---: |
| Web Application Architecture |
 


- Big data/Batch processing:
    - These applications are usually in the backend and not directly seen by users.
    - The applications process and produce information used by other applications.
    - Examples: recommendation engines for commerce web sites, Google Analytics.



| <img src="../../images/google_analytics.jpeg"> |
| :---: |
| Google Analytics |


    
| <img src="../../images/batch_1.jpeg"> |
| :---: |
| [Batch Processing](https://www.datasciencecentral.com/profiles/blogs/batch-vs-real-time-data-processing) |
<hr style="height:2px;">

- Each stage in batch processing is multiple, smaller jobs/applications that have to run in specific orders.


- [MapReduce](https://en.wikipedia.org/wiki/MapReduce) and [Hadoop](https://en.wikipedia.org/wiki/Apache_Hadoop) are modern approaches to batch processing.


- I am going to try to find a way to do a little of this, but setting up all of the SW is complex.


| <img src="../../images/map_reduce_1.jpeg"> |
| :---: |
| __Map-Reduce__ |

- Data Warehouse Database:
    - Operational databases create-retrieve-update-delete data during on-line processing.
    - Data Warehouse is a transformed copy of the data for more complex, read only queries and reports.
    - We will do OLAP and analysis in the course, but on a small scale. The scenarios assume that ETL has already loaded the simple warehouse.
    
| <img src="../../images/data_warehouse_architecture.jpg"> |
| :---: |
| __Data Warehouse__ |

## Other Classifications and Models

- Another classification approach is to think of the _functions_ the databases support.


- A data processing system may involve some combination of the following functions
    - Conversion - converting data to another format.
    - Validation – Ensuring that supplied data is "clean, correct and useful."
    - Sorting – "arranging items in some sequence and/or in different sets."
    - Summarization – reducing detail data to its main points.
    - Aggregation – combining multiple pieces of data.
    - Analysis – the "collection, organization, analysis, interpretation and presentation of data.".
    - Reporting – list detail or summary data or computed information.
    
    
- Both SQL/online and batch/MapReduce/Hadoop have operators/steps implementing the functions. For example,
    - Summarization can be a Reducer in MapReduce and a GROUP BY operator in RDBs
    - Many batch systems use SQL and extensions as the language for programming mappers, shufflers, reducers, etc.
    
    
- A third classification approach
    - Operational Database: SSOL, CourseWorks, etc. are examples.
    - External Database: On-line banking, IMDB, etc. are examples.
    - End User Database: The local caches of data for mobile applications are an example.
    - Distributed Database
    - Data Warehouse Database:
        - Operational databases create-retrieve-update-delete data during on-line processing.
        - Data Warehouse is a transformed copy of the data for more complex, read only queries and reports.
    - Analytical Database
    - Hypermedia Database: Database for storing, retrieving, categorizing, searching, etc. linked, unstructured content like documents, images, recording, etc. You can consider the web itself to be a Hypermedia Database.
    
    

## Web Application

<hr style="height:1px;">

| <img src="../../images/two-three-tier.jpeg"> |
| :---: |
| __Database Architectures__ |

<hr style="height:1px;">

<hr style="height:2px;">

| <img src="../../images/mult-tier-application.jpg"> |
| :---: |
| __Application Architecture__ |

<hr style="height:2px;">

<hr style="height:2px;">

| <img src="../../images/webapp.jpeg"> |
| :---: |
| __Application Structure__ |

<hr style="height:2px;">

- We will do a very simple version.
    - Not focus on the web front-end. This is an extremely complex area.
    - Our next focus will be REST APIs accessing the relational data in Lahman 2019.
    
    
- I will provide a starter project that has the application server and framework in it.


<hr style="height:1px;">

| <img src="../../images/hw2_intro.jpeg"> |
| :---: |
| __HW2 Concept__ |

<hr style="height:1px;">

## Simple Demo

- Demo Web Application


# Back to Our Sample Application

- The first two parts of the application would require:
    - Player and team performance:
        - The ability to query information about players, teams, performance, etc.
        - The ability to enter and update information.
    - Allow users playing fantasy baseball to:
        - Register with the site.
        - Create a team.
        - Add and remove players from a team.
        

- Data modeling: Non-trivial applications require a well-design data model.
    - Task 1: Player and team performance is primarily _bottom-up_ aka _reverse engineering_ of an existing set of data.
    - Task 2: Users, fantasy teams, ... is primarily _top-down_ aka _forward engineering_ of a new database.
    
    
- To support application operations, we will need to:
    - Write some relatively sophisticated SQL statements.
    - Clean up the data.
    - Implement integrity constraints.
    - ... ...

# Finding People

## Problem Definition

- Provide a web UI for querying and updating information about Lahman2019raw.People.

| Common Data Operation | RDB Operation | REST Method |
| :---: | :---: | :---: |
| CREATE | INSERT | POST |
| RETRIEVE | SELECT | GET |
| UPDATE | UPDATE | POST |
| DELETE | DELETE | DELETE |
||| __Data Operations__ |
 


- The starting point will be understanding how to use SQL to perform queries.

## SELECT Operation $-$ Reminder

- Basic format:

```
SELECT column1, column2, ...
FROM table_name
WHERE condition;
```

- The _column list_ is actually the formal relational _project_ ($\pi$) operation, and defines a subset of the columns.


- The ```WHERE``` clause performs the formal relational _select_ operation ($\sigma$).


- The ```WHERE``` clause is similar to an ```IF``` condition in most programming languages.

| <img src="../../images/sql_where.jpeg"> |
| :---: |
| [SQL Where] (https://www.w3schools.com/sql/sql_where.asp) Comparison Operators |


- There are additional _boolean_ operators for combining comparisons: ```AND, OR, NOT, EXISTS.```

## How do You Learn SQL?

- Old joke:
    - "How do you get to Carnegie Hall?"
    - "Practice."
    
    
__Find People by Name__

In [5]:
%sql select * from lahman2019raw.people where nameLast='Ferguson' and nameFirst='Donald'

0 rows affected.


[]

In [7]:
%sql select * from lahman2019raw.people where nameLast='Ferguson' or nameFirst='Donald' limit 10;

10 rows affected.


[('fergual01', '1897', '2', '16', 'USA', 'NJ', 'Montclair', '1976', '4', '26', 'USA', 'CA', 'Sepulveda', 'Alex', 'Ferguson', 'James Alexander', '180', '72', 'R', 'R', '1918-08-16', '1929-05-18', 'ferga101', 'fergual01'),
 ('fergubo01', '1845', '1', '31', 'USA', 'NY', 'Brooklyn', '1894', '5', '3', 'USA', 'NY', 'Brooklyn', 'Bob', 'Ferguson', 'Robert Vavasour', '149', '69', 'B', 'R', '1871-05-18', '1884-07-01', 'fergb101', 'fergubo01'),
 ('fergubo02', '1919', '4', '18', 'USA', 'AL', 'Birmingham', '2008', '5', '23', 'USA', 'AL', 'Wetumpka', 'Bob', 'Ferguson', 'Robert Lester', '180', '73', 'R', 'R', '1944-04-29', '1944-06-03', 'fergb102', 'fergubo02'),
 ('ferguca01', '1996', '7', '2', 'USA', 'OH', 'Columbus', '', '', '', '', '', '', 'Caleb', 'Ferguson', 'Caleb Paul', '215', '75', 'R', 'L', '2018-06-06', '2018-09-26', 'fergc001', 'ferguca01'),
 ('ferguch01', '1863', '4', '17', 'USA', 'VA', 'Charlottesville', '1888', '4', '29', 'USA', 'PA', 'Philadelphia', 'Charlie', 'Ferguson', 'Charles J.', '165', '72', 'B', 'R', '1884-05-01', '1887-10-08', 'fergc101', 'ferguch01'),
 ('ferguch02', '1875', '5', '10', 'USA', 'MI', 'Meridian', '1931', '5', '17', 'USA', 'MI', 'Sault Ste. Marie', 'Charlie', 'Ferguson', 'Charles Augustus', '', '71', '', 'R', '1901-09-20', '1901-09-20', 'fergc102', 'ferguch02'),
 ('ferguge01', '1883', '8', '27', 'USA', 'IN', 'Ellsworth', '1943', '9', '5', 'USA', 'FL', 'Montverde', 'Cecil', 'Ferguson', 'Cecil Benoni', '165', '70', 'R', 'R', '1906-04-19', '1911-07-21', 'fergg101', 'ferguge01'),
 ('fergujo01', '1946', '9', '19', 'USA', 'CA', 'San Francisco', '', '', '', '', '', '', 'Joe', 'Ferguson', 'Joseph Vance', '200', '74', 'R', 'R', '1970-09-12', '1983-06-17', 'fergj101', 'fergujo01'),
 ('harrido01', '1967', '11', '12', 'USA', 'TX', 'Waco', '', '', '', '', '', '', 'Donald', 'Harris', 'Donald', '185', '73', 'R', 'R', '1991-09-04', '1993-10-02', 'harrd001', 'harrido01'),
 ('lutzdo01', '1989', '2', '6', 'USA', 'NY', 'Watertown', '', '', '', '', '', '', 'Donald', 'Lutz', 'Donald Thomas', '240', '75', 'L', 'R', '2013-04-29', '2014-09-24', 'lutzd001', 'lutzdo01')]

__Find by name and age range:__ Which people that we know have died, and with ```nameLast``` Ferguson, and who were born more than 50 years ago.

In [9]:
%sql select year(now()) as current_year

1 rows affected.


[(2019,)]

In [10]:
%sql select * from people where nameLast='Ferguson' and ((2019 - birthYear) > 50) and (deathYear != '')  

6 rows affected.


[('fergual01', '1897', '2', '16', 'USA', 'NJ', 'Montclair', '1976', '4', '26', 'USA', 'CA', 'Sepulveda', 'Alex', 'Ferguson', 'James Alexander', '180', '72', 'R', 'R', '1918-08-16', '1929-05-18', 'ferga101', 'fergual01'),
 ('fergubo01', '1845', '1', '31', 'USA', 'NY', 'Brooklyn', '1894', '5', '3', 'USA', 'NY', 'Brooklyn', 'Bob', 'Ferguson', 'Robert Vavasour', '149', '69', 'B', 'R', '1871-05-18', '1884-07-01', 'fergb101', 'fergubo01'),
 ('fergubo02', '1919', '4', '18', 'USA', 'AL', 'Birmingham', '2008', '5', '23', 'USA', 'AL', 'Wetumpka', 'Bob', 'Ferguson', 'Robert Lester', '180', '73', 'R', 'R', '1944-04-29', '1944-06-03', 'fergb102', 'fergubo02'),
 ('ferguch01', '1863', '4', '17', 'USA', 'VA', 'Charlottesville', '1888', '4', '29', 'USA', 'PA', 'Philadelphia', 'Charlie', 'Ferguson', 'Charles J.', '165', '72', 'B', 'R', '1884-05-01', '1887-10-08', 'fergc101', 'ferguch01'),
 ('ferguch02', '1875', '5', '10', 'USA', 'MI', 'Meridian', '1931', '5', '17', 'USA', 'MI', 'Sault Ste. Marie', 'Charlie', 'Ferguson', 'Charles Augustus', '', '71', '', 'R', '1901-09-20', '1901-09-20', 'fergc102', 'ferguch02'),
 ('ferguge01', '1883', '8', '27', 'USA', 'IN', 'Ellsworth', '1943', '9', '5', 'USA', 'FL', 'Montverde', 'Cecil', 'Ferguson', 'Cecil Benoni', '165', '70', 'R', 'R', '1906-04-19', '1911-07-21', 'fergg101', 'ferguge01')]

- Can I make that cleaner?

In [14]:
%%sql
select
    nameLast as `Last name`,
    nameFirst as `First name`,
    concat(birthMonth, '/', birthDay, '/', birthYear) as `Date of birth`,
    concat(deathMonth, '/', deathDay, '/', deathYear) as `Date of death`
from
    people
where
    nameLast='Ferguson' and ((2019 - birthYear) > 50) and (deathYear != '')  

6 rows affected.


[('Ferguson', 'Alex', '2/16/1897', '4/26/1976'),
 ('Ferguson', 'Bob', '1/31/1845', '5/3/1894'),
 ('Ferguson', 'Bob', '4/18/1919', '5/23/2008'),
 ('Ferguson', 'Charlie', '4/17/1863', '4/29/1888'),
 ('Ferguson', 'Charlie', '5/10/1875', '5/17/1931'),
 ('Ferguson', 'Cecil', '8/27/1883', '9/5/1943')]

- Some comments:
    - You can rename (alias) columns and tables using ```as```
    - There are many, many functions that you can apply to columns in the column clause, ```WHERE``` clause, etc.
        - Number and math functions.
        - String functions.
        - Time and date functions.
        - ... ...


## SQL Functions

| __Function__      | __Description __                                                                                                                                                         |
|---------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| ASCII         | Returns the ASCII value for the specific character                                                                                                                   |
| CHAR          | Returns the character based on the ASCII code                                                                                                                        |
| CHARINDEX     | Returns the position of a substring in a string                                                                                                                      |
| CONCAT        | Adds two or more strings together                                                                                                                                    |
| Concat with + | Adds two or more strings together                                                                                                                                    |
| CONCAT_WS     | Adds two or more strings together with a separator                                                                                                                   |
| DATALENGTH    | Returns the number of bytes used to represent an expression                                                                                                          |
| DIFFERENCE    | Compares two SOUNDEX values, and returns an integer value                                                                                                            |
| FORMAT        | Formats a value with the specified format                                                                                                                            |
| LEFT          | Extracts a number of characters from a string (starting from left)                                                                                                   |
| LEN           | Returns the length of a string                                                                                                                                       |
| LOWER         | Converts a string to lower-case                                                                                                                                      |
| LTRIM         | Removes leading spaces from a string                                                                                                                                 |
| NCHAR         | Returns the Unicode character based on the number code                                                                                                               |
| PATINDEX      | Returns the position of a pattern in a string                                                                                                                        |
| QUOTENAME     | Returns a Unicode string with delimiters added to make the string a valid SQL Server delimited identifier                                                            |
| REPLACE       | Replaces all occurrences of a substring within a string, with a new substring                                                                                        |
| REPLICATE     | Repeats a string a specified number of times                                                                                                                         |
| REVERSE       | Reverses a string and returns the result                                                                                                                             |
| RIGHT         | Extracts a number of characters from a string (starting from right)                                                                                                  |
| RTRIM         | Removes trailing spaces from a string                                                                                                                                |
| SOUNDEX       | Returns a four-character code to evaluate the similarity of two strings                                                                                              |
| SPACE         | Returns a string of the specified number of space characters                                                                                                         |
| STR           | Returns a number as string                                                                                                                                           |
| STUFF         | Deletes a part of a string and then inserts another part into the string, starting at a specified position                                                           |
| SUBSTRING     | Extracts some characters from a string                                                                                                                               |
| TRANSLATE     | Returns the string from the first argument after the characters specified in the second argument are translated into the characters specified in the third argument. |
| TRIM          | Removes leading and trailing spaces (or other specified characters) from a string                                                                                    |
| UNICODE       | Returns the Unicode value for the first character of the input expression                                                                                            |
| UPPER         | Converts a string to upper-case                                                                                                                                      |
| | [SQL String Functions](https://www.w3schools.com/sql/sql_ref_sqlserver.asp) |

| __Function__ | __Description __ |                                                                                |
|----------|---------------------------------------------------------------------------------------------|
| ABS      | Returns the absolute value of a number                                                      |
| ACOS     | Returns the arc cosine of a number                                                          |
| ASIN     | Returns the arc sine of a number                                                            |
| ATAN     | Returns the arc tangent of a number                                                         |
| ATN2     | Returns the arc tangent of two numbers                                                      |
| AVG      | Returns the average value of an expression                                                  |
| CEILING  | Returns the smallest integer value that is >= a number                                      |
| COUNT    | Returns the number of records returned by a select query                                    |
| COS      | Returns the cosine of a number                                                              |
| COT      | Returns the cotangent of a number                                                           |
| DEGREES  | Converts a value in radians to degrees                                                      |
| EXP      | Returns e raised to the power of a specified number                                         |
| FLOOR    | Returns the largest integer value that is <= to a number                                    |
| LOG      | Returns the natural logarithm of a number, or the logarithm of a number to a specified base |
| LOG10    | Returns the natural logarithm of a number to base 10                                        |
| MAX      | Returns the maximum value in a set of values                                                |
| MIN      | Returns the minimum value in a set of values                                                |
| PI       | Returns the value of PI                                                                     |
| POWER    | Returns the value of a number raised to the power of another number                         |
| RADIANS  | Converts a degree value into radians                                                        |
| RAND     | Returns a random number                                                                     |
| ROUND    | Rounds a number to a specified number of decimal places                                     |
| SIGN     | Returns the sign of a number                                                                |
| SIN      | Returns the sine of a number                                                                |
| SQRT     | Returns the square root of a number                                                         |
| SQUARE   | Returns the square of a number                                                              |
| SUM      | Calculates the sum of a set of values                                                       |
| TAN      | Returns the tangent of a number                                                             |
| | [SQL Numeric Functions](https://www.w3schools.com/sql/sql_ref_sqlserver.asp) |

| __Function__          | __Description__                                                          |
|-------------------|-----------------------------------------------------------------------|
| CURRENT_TIMESTAMP | Returns the current date and time                                     |
| DATEADD           | Adds a time/date interval to a date and then returns the date         |
| DATEDIFF          | Returns the difference between two dates                              |
| DATEFROMPARTS     | Returns a date from the specified parts (year, month, and day values) |
| DATENAME          | Returns a specified part of a date (as string)                        |
| DATEPART          | Returns a specified part of a date (as integer)                       |
| DAY               | Returns the day of the month for a specified date                     |
| GETDATE           | Returns the current database system date and time                     |
| GETUTCDATE        | Returns the current database system UTC date and time                 |
| ISDATE            | Checks an expression and returns 1 if it is a valid date, otherwise 0 |
| MONTH             | Returns the month part for a specified date (a number from 1 to 12)   |
| SYSDATETIME       | Returns the date and time of the SQL Server                           |
| YEAR              | Returns the year part for a specified date                            |
| | [SQL Time/Date Functions](https://www.w3schools.com/sql/sql_ref_sqlserver.asp) |

| __Function__        | __Description__                                                                         |
|-----------------|-------------------------------------------------------------------------------------|
| CAST            | Converts a value (of any type) into a specified datatype                            |
| COALESCE        | Returns the first non-null value in a list                                          |
| CONVERT         | Converts a value (of any type) into a specified datatype                            |
| CURRENT_USER    | Returns the name of the current user in the SQL Server database                     |
| IIF             | Returns a value if a condition is TRUE, or another value if a condition is FALSE    |
| ISNULL          | Return a specified value if the expression is NULL, otherwise return the expression |
| ISNUMERIC       | Tests whether an expression is numeric                                              |
| NULLIF          | Returns NULL if two expressions are equal                                           |
| SESSION_USER    | Returns the name of the current user in the SQL Server database                     |
| SESSIONPROPERTY | Returns the session settings for a specified option                                 |
| SYSTEM_USER     | Returns the login name for the current user                                         |
| USER_NAME       | Returns the database user name based on the specified id                            |
| | [SQL Advanced Functions](https://www.w3schools.com/sql/sql_ref_sqlserver.asp) |

- __Note:__ These are the standard functions. Specific database products implement an extended set of functions.

# An Aside $-$ iPython Magics

## The Magic

- You keep doing things like ...

```
%load_ext sql
%sql mysql+pymysql://root:dbuserdbuser@localhost/lahman2019raw
%sql select * from people where playerid='willite01'
```

- and

```
%%sql
select
    nameLast as `Last name`,
    nameFirst as `First name`,
    concat(birthMonth, '/', birthDay, '/', birthYear) as `Date of birth`,
    concat(deathMonth, '/', deathDay, '/', deathYear) as `Date of death`
from
    people
where
    nameLast='Ferguson' and ((2019 - birthYear) > 50) and (deathYear != '')  
```


| <img src="../../images/what-is-this-sorcery.jpg" > |
| :---: |
| __Some Sorcery__ |

## iPython/Jupyter Notebook Architecture

| <img src="../../images/notebook_components.png" > |
| :---: |
| [iPython Notebook Architecture](https://jupyter.readthedocs.io/en/latest/architecture/how_jupyter_ipython_work.html) |


- There are several good explanations of interactive Python, iPython notebooks, etc:
    - https://jupyter.readthedocs.io/en/latest/architecture/how_jupyter_ipython_work.html
    - https://ipython-books.github.io/chapter-3-mastering-the-jupyter-notebook/
    
    
- You do not need to understand this material for the course.


- In lectures, I am using Jupyter notebooks.
    - There is an ecosystem of plug-ins and extensions that add features to the base notebook capabilities.
    - The ```%sql magic function``` is one of the extensions. 
    
    
- "IPython will treat any line whose first character is a % as a special call to a ‘magic’ function. These allow you to control the behavior of IPython itself, plus a lot of system-type features. They are all prefixed with a % character, but parameters are given without parentheses or quote." (https://ipython.readthedocs.io/en/stable/interactive/reference.html#magic)

In [2]:
print("I can call a Magic with '%'")
%magic

I can call a Magic with '%'


- ```%load_ext sql``` is calling the magic function ```load_extension.``` This
    - Loads the extension module
    - The ```%sql``` magic function.
  
  
- This is all FYI. The [iPython](https://ipython.readthedocs.io/en/stable/config/custommagics.html?highlight=magic) documentation explains how to implement Magics.     

## The Specific Magic

- To run the examples that use %sql, you will have to install an extension to your iPython/Jupyter notebooks.


- The extension and installation instruction are at: https://pypi.org/project/ipython-sql/


- You can come to office hours (CAs, mine) if you need help.

| <img src="../../images/install_wizard.jpg"> |
| :---: |
| __Installation Wizard__ |

## You Still Need Connections

- What about ```%sql mysql+pymysql://dbuser:dbuser@localhost/lahman2017```?

| <img src="../../images/db-connection.jpg"> |
| :---: |
| __Database Server and Connection__ |


- There are typically two processes (running programs) in a database application.
    - The database server, which processes database commands.
    - The client application that sends commands to and receives responses from the database server.
    
    
- The magic statement defines a database connection.


"A Database connection is facility in computer science that allows client software to talk to database server software, whether on the same machine or not. A connection is required to send commands and receive answers, usually in the form of a result set.

Connections are a key concept in data-centric programming. Since some DBMS engines require considerable time to connect connection pooling was invented to improve performance. No command can be performed against a database without an "open and available" connection to it.

Connections are built by supplying an underlying driver or provider with a connection string, which is a way of addressing a specific database or server and instance as well as user authentication credentials (for example, Server=sql_box;Database=Common;User ID=uid;Pwd=password;). Once a connection has been built it can be opened and closed at will, and properties (such as the command time-out length, or transaction, if one exists) can be set. The Connection String is composed of a set of key/value pairs as dictated by the data access interface and data provider being used." (https://en.wikipedia.org/wiki/Database_connection)

- Modifying the diagram above to add the DB server

| <img src="../../images/notebook_and_db.jpeg"> |
| :---: |
| __Notebook and DB__

# INSERT-ing/UPDATE-ing People

## Concept

- At some point, someone is going to have to add additional information to or change information in the people table.


- No problem. We now how to do INSERT!


- What are the columns in the table?



In [17]:
%sql describe lahman2019raw.people

24 rows affected.


[('playerID', 'text', 'YES', '', None, ''),
 ('birthYear', 'text', 'YES', '', None, ''),
 ('birthMonth', 'text', 'YES', '', None, ''),
 ('birthDay', 'text', 'YES', '', None, ''),
 ('birthCountry', 'text', 'YES', '', None, ''),
 ('birthState', 'text', 'YES', '', None, ''),
 ('birthCity', 'text', 'YES', '', None, ''),
 ('deathYear', 'text', 'YES', '', None, ''),
 ('deathMonth', 'text', 'YES', '', None, ''),
 ('deathDay', 'text', 'YES', '', None, ''),
 ('deathCountry', 'text', 'YES', '', None, ''),
 ('deathState', 'text', 'YES', '', None, ''),
 ('deathCity', 'text', 'YES', '', None, ''),
 ('nameFirst', 'text', 'YES', '', None, ''),
 ('nameLast', 'text', 'YES', '', None, ''),
 ('nameGiven', 'text', 'YES', '', None, ''),
 ('weight', 'text', 'YES', '', None, ''),
 ('height', 'text', 'YES', '', None, ''),
 ('bats', 'text', 'YES', '', None, ''),
 ('throws', 'text', 'YES', '', None, ''),
 ('debut', 'text', 'YES', '', None, ''),
 ('finalGame', 'text', 'YES', '', None, ''),
 ('retroID', 'text', 'YES', '', None, ''),
 ('bbrefID', 'text', 'YES', '', None, '')]

- So, let's run an ```INSERT.``` I always wanted to play Major League Baseball.

In [19]:
%%sql
insert into lahman2019raw.people
    (nameLast, nameFirst, height, weight, throws, bats, birthYear)
    values(
        'Ferguson', 'Donald', '70', 'None of your business', 'Banana', 'seldom', 'Yes')

1 rows affected.


[]

- What did I insert?

In [20]:
%sql select * from lahman2019raw.people where nameLast='Ferguson' and nameFirst='Donald'

1 rows affected.


[(None, 'Yes', None, None, None, None, None, None, None, None, None, None, None, 'Donald', 'Ferguson', None, 'None of your business', '70', 'seldom', 'Banana', None, None, None, None)]

- I am not sure that I would be happy with what happened. I am pretty sure that:
    - ```playerID``` cannot be ```NULL```
    - ```None of your business``` is not an acceptable value for ```weight.``` Same for ```throws``` and ```banana.```
    
    
- We probably want to put some _constraints_ on the values of the columns.

## Integrity Constraints

<hr style="height:2px">

| <img src="../../images/integrity_0.jpeg"> |
| :---: |
| [Integrity Constraints](https://www.javatpoint.com/dbms-integrity-constraints) |

<hr style="height:2px">

- The most common type of domain constraints are _valid types constraints._

- Well, What are my Options?


| <img src="../../images/MySQL-Data-Types.jpg" > |
| :---: |
| __MySQL Data Types__ |



- One of the strengths of the relational model is support for powerful [integrity constraints]()

| CONSTRAINT  | DESCRIPTION                                                                                                                                                                                                               |
|-------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| NOT NULL    | In MySQL NOT NULL constraint allows to specify that a column can not contain any NULL value. MySQL NOT NULL can be used to CREATE and ALTER a table.                                                                      |
| UNIQUE      | The UNIQUE constraint in MySQL does not allow to insert a duplicate value in a column. The UNIQUE constraint maintains the uniqueness of a column in a table. More than one UNIQUE column can be used in a table.         |
| PRIMARY KEY | A PRIMARY KEY constraint for a table enforces the table to accept unique data for a specific column and this constraint creates a unique index for accessing the table faster.                                            |
| __FOREIGN KEY__ | __A FOREIGN KEY in MySQL creates a link between two tables by one specific column of both tables. The specified column in one table must be a PRIMARY KEY and referred by the column of another table known as FOREIGN KEY.__ |
| CHECK       | A CHECK constraint controls the values in the associated column. The CHECK constraint determines whether the value is valid or not from a logical expression.                                                             |
| DEFAULT     | In a MySQL table, each column must contain a value ( including a NULL). While inserting data into a table, if no value is supplied to a column, then the column gets the value set as DEFAULT.                            |

<hr style="height:2px">

| <img src="../../images/integrity_1.jpeg"> |
| :---: |
| __Integrity Constraints__ |

<hr style="height:2px">

<hr style="height:2px">

| <img src="../../images/integrity_2.jpeg"> |
| :---: |
| __Integrity Constraints__ |

<hr style="height:2px">

## Let's Apply to People

### Set Up

- I am going to keep the original data in case I make a mistake, and also for _data lineage and data provenance._


- "Data lineage includes the data origin, what happens to it and where it moves over time.[1] Data lineage gives visibility while greatly simplifying the ability to trace errors back to the root cause in a data analytics process.
<br><br>
...
...
<br><br>
Data provenance provides a historical record of the data and its origins." (https://en.wikipedia.org/wiki/Data_lineage#Data_provenance)


- I made another schema, ```lahman2019clean```

In [21]:
%sql create schema lahman2019clean;

1 rows affected.


[]

In [22]:
%sql use lahman2019clean;

0 rows affected.


[]

- I am now going to make a copy of the data using a special form of ```SELECT``` and ```CREATE TABLE```

In [23]:
%sql create table people as select * from lahman2019raw.people;

19618 rows affected.


[]

In [24]:
%sql select * from people limit 10;

10 rows affected.


[('aardsda01', '1981', '12', '27', 'USA', 'CO', 'Denver', '', '', '', '', '', '', 'David', 'Aardsma', 'David Allan', '215', '75', 'R', 'R', '2004-04-06', '2015-08-23', 'aardd001', 'aardsda01'),
 ('aaronha01', '1934', '2', '5', 'USA', 'AL', 'Mobile', '', '', '', '', '', '', 'Hank', 'Aaron', 'Henry Louis', '180', '72', 'R', 'R', '1954-04-13', '1976-10-03', 'aaroh101', 'aaronha01'),
 ('aaronto01', '1939', '8', '5', 'USA', 'AL', 'Mobile', '1984', '8', '16', 'USA', 'GA', 'Atlanta', 'Tommie', 'Aaron', 'Tommie Lee', '190', '75', 'R', 'R', '1962-04-10', '1971-09-26', 'aarot101', 'aaronto01'),
 ('aasedo01', '1954', '9', '8', 'USA', 'CA', 'Orange', '', '', '', '', '', '', 'Don', 'Aase', 'Donald William', '190', '75', 'R', 'R', '1977-07-26', '1990-10-03', 'aased001', 'aasedo01'),
 ('abadan01', '1972', '8', '25', 'USA', 'FL', 'Palm Beach', '', '', '', '', '', '', 'Andy', 'Abad', 'Fausto Andres', '184', '73', 'L', 'L', '2001-09-10', '2006-04-13', 'abada001', 'abadan01'),
 ('abadfe01', '1985', '12', '17', 'D.R.', 'La Romana', 'La Romana', '', '', '', '', '', '', 'Fernando', 'Abad', 'Fernando Antonio', '220', '73', 'L', 'L', '2010-07-28', '2017-10-01', 'abadf001', 'abadfe01'),
 ('abadijo01', '1850', '11', '4', 'USA', 'PA', 'Philadelphia', '1905', '5', '17', 'USA', 'NJ', 'Pemberton', 'John', 'Abadie', 'John W.', '192', '72', 'R', 'R', '1875-04-26', '1875-06-10', 'abadj101', 'abadijo01'),
 ('abbated01', '1877', '4', '15', 'USA', 'PA', 'Latrobe', '1957', '1', '6', 'USA', 'FL', 'Fort Lauderdale', 'Ed', 'Abbaticchio', 'Edward James', '170', '71', 'R', 'R', '1897-09-04', '1910-09-15', 'abbae101', 'abbated01'),
 ('abbeybe01', '1869', '11', '11', 'USA', 'VT', 'Essex', '1962', '6', '11', 'USA', 'VT', 'Colchester', 'Bert', 'Abbey', 'Bert Wood', '175', '71', 'R', 'R', '1892-06-14', '1896-09-23', 'abbeb101', 'abbeybe01'),
 ('abbeych01', '1866', '10', '14', 'USA', 'NE', 'Falls City', '1926', '4', '27', 'USA', 'CA', 'San Francisco', 'Charlie', 'Abbey', 'Charles S.', '169', '68', 'L', 'L', '1893-08-16', '1897-08-19', 'abbec101', 'abbeych01')]

### Some Basic Cleanup
<br><br>
<center>
<span style="color:red;font-size:48px;line-height:1.2;">Do not run the SQL. <br>I already ran and cleaned up the data.</span>
</center>

#### Primary Key

- We know that ```playerID``` is the primary key. How?
    - I told you.
    - I read the ```README.TXT```
    - I checked.
    
    
- We will cover ```GROUP BY``` next lecture, but this is a useful probe query.

In [25]:
%%sql
    select playerid, count(playerid) as no_of_occurences from people
        group by playerid
        order by no_of_occurences desc
        limit 10;

10 rows affected.


[('alleyge01', 1),
 ('collaal01', 1),
 ('fulmemi01', 1),
 ('muelldo01', 1),
 ('tinglro01', 1),
 ('allisdo01', 1),
 ('collido01', 1),
 ('funkto01', 1),
 ('muffebi01', 1),
 ('tiptojo01', 1)]

- I can also use this to help figure out other fields.

In [26]:
%%sql
select throws, count(throws) as no_of_occurences from people
        group by throws
        order by no_of_occurences desc
        limit 10;

5 rows affected.


[('R', 14877), ('L', 3760), ('', 979), ('S', 1), ('Banana', 1)]

- We will get to this in a second. Back to primary key. First, I need to get rid of the bad row I inserted.

In [27]:
%sql delete from people where playerid is NULL;

1 rows affected.


[]

- Now, alter the table.

```
ALTER TABLE `lahman2019clean`.`people` 
CHANGE COLUMN `playerID` `playerID` VARCHAR(12) NOT NULL ,
ADD PRIMARY KEY (`playerID`);

```

- How did I know that 12 characters was enough for ```playerID?```

In [29]:
%sql select max(length(playerid)) as maximum_id_length from people

1 rows affected.


[(9,)]

- Let's look at the table again.

In [30]:
%sql describe people

24 rows affected.


[('playerID', 'varchar(16)', 'NO', 'PRI', None, ''),
 ('birthYear', 'text', 'YES', '', None, ''),
 ('birthMonth', 'text', 'YES', '', None, ''),
 ('birthDay', 'text', 'YES', '', None, ''),
 ('birthCountry', 'text', 'YES', '', None, ''),
 ('birthState', 'text', 'YES', '', None, ''),
 ('birthCity', 'text', 'YES', '', None, ''),
 ('deathYear', 'text', 'YES', '', None, ''),
 ('deathMonth', 'text', 'YES', '', None, ''),
 ('deathDay', 'text', 'YES', '', None, ''),
 ('deathCountry', 'text', 'YES', '', None, ''),
 ('deathState', 'text', 'YES', '', None, ''),
 ('deathCity', 'text', 'YES', '', None, ''),
 ('nameFirst', 'text', 'YES', '', None, ''),
 ('nameLast', 'text', 'YES', '', None, ''),
 ('nameGiven', 'text', 'YES', '', None, ''),
 ('weight', 'text', 'YES', '', None, ''),
 ('height', 'text', 'YES', '', None, ''),
 ('bats', 'text', 'YES', '', None, ''),
 ('throws', 'text', 'YES', '', None, ''),
 ('debut', 'text', 'YES', '', None, ''),
 ('finalGame', 'text', 'YES', '', None, ''),
 ('retroID', 'text', 'YES', '', None, ''),
 ('bbrefID', 'text', 'YES', '', None, '')]

In [32]:
%sql show keys from people

1 rows affected.


[('people', 0, 'PRIMARY', 1, 'playerID', 'A', 19571, None, None, '', 'BTREE', '', '', 'YES', None)]

- Let's take a look at the table again.

### Numeric Columns (and NULL)

- I am pretty sure that some of these columns are numbers, not free form text.

In [35]:
%sql select height, count(height) as no_of_occurrences from people  group by height limit 10;

10 rows affected.


[('75', 1761),
 ('72', 3094),
 ('73', 2592),
 ('71', 2512),
 ('68', 716),
 ('70', 1928),
 ('78', 213),
 ('74', 2492),
 ('76', 1062),
 ('69', 1104)]

- Alrighty then, let's convert to an ```INT.``` I know this is going to fail, for the same reason it would have failed if you tried to import this columns as an integer.

In [38]:
try:
    %sql ALTER TABLE `lahman2019clean`.`people` CHANGE COLUMN `weight` `weight` INT NULL DEFAULT NULL ;
except Exception as e:
    print(e)

(pymysql.err.InternalError) (1366, "Incorrect integer value: '' for column 'weight' at row 21")
[SQL: ALTER TABLE `lahman2019clean`.`people` CHANGE COLUMN `weight` `weight` INT NULL DEFAULT NULL ;]
(Background on this error at: http://sqlalche.me/e/2j85)


- This is historical data. The compilers did not know how much some people weighed, and marked this fact by setting weight to ```''```


- The relational model handles this with ```NULL.```

In [39]:
%sql update people set weight=NULL where weight=''

825 rows affected.


[]

- and ...

In [40]:
try:
    %sql ALTER TABLE `lahman2019clean`.`people` CHANGE COLUMN `weight` `weight` INT NULL DEFAULT NULL ;
except Exception as e:
    print(e)

19617 rows affected.


- "Codd's twelve rules are a set of thirteen rules (numbered zero to twelve) proposed by Edgar F. Codd, a pioneer of the relational model for databases, designed to define what is required from a database management system in order for it to be considered relational, i.e., a relational database management system (RDBMS). They are sometimes jokingly referred to as "Codd's Twelve Commandments." (https://en.wikipedia.org/wiki/Codd%27s_12_rules)


- Ed Codd and I were both IBM Fellows. Unlike most IBM Fellows, you have to listen to Ed Codd.


- __Rule 3__ - Systematic treatment of null values: Null values (distinct from the empty character string or a string of blank characters and distinct from zero or any other number) are supported in fully relational DBMS for representing missing information and inapplicable information in a systematic way, independent of data type.


- ```weight = NULL``` means that I do not have a valid value.


- ```weight = ''``` means the person weighed ```''``` pounds.


- Some examples of why this matters.

In [44]:
%sql select 2 + '' as math1;

1 rows affected.


[(2.0,)]

In [43]:
%sql select 2 + NULL as math2;

1 rows affected.


[(None,)]

- If I am manipulating numbers, I do not want to accidentally compute a result despite the fact that I did not actually know the value of one of the operands.

<hr style="height:2px">

| <img src="../../images/null_1.jpeg"> |
| :---: |
| __NULL__ |

<hr style="height:2px">

<hr style="height:2px">

| <img src="../../images/null_2.jpeg"> |
| :---: |
| __NULL__ |

<hr style="height:2px">

- Wrapping up, there are a few columns that are clearly numbers. I can do the same things with them: 1) Remove the ```''``` and convert to numbers.


- In general, I want to convert everything of the form ```''``` to ```NULL.```


- We will do a couple of examples.

### NULLs



In [45]:
%sql select nameLast, nameFirst from people where nameLast='' or nameFirst='';

37 rows affected.


[('Boland', ''),
 ('Booth', ''),
 ('Carroll', ''),
 ('Edwards', ''),
 ('Evans', ''),
 ('Franklin', ''),
 ('Gavern', ''),
 ('Harrison', ''),
 ('Hellings', ''),
 ('Higby', ''),
 ('Hillebrand', ''),
 ('Jones', ''),
 ('Jones', ''),
 ('Leonard', ''),
 ('Lewis', ''),
 ('Macey', ''),
 ('McBride', ''),
 ('McDoolan', ''),
 ('McRemer', ''),
 ('Murphy', ''),
 ("O'Rourke", ''),
 ('Pierce', ''),
 ('Quinlan', ''),
 ('Quinn', ''),
 ('Richardson', ''),
 ('Scott', ''),
 ('Shaffer', ''),
 ('Sheridan', ''),
 ('Smith', ''),
 ('Spencer', ''),
 ('Stafford', ''),
 ('Sterling', ''),
 ('Stoddard', ''),
 ('Sullivan', ''),
 ('Sweigert', ''),
 ('Wills', ''),
 ('Wood', '')]

- Are there any cases where I do not know the ```nameLast?```

In [46]:
%sql select * from people where nameLast=''

0 rows affected.


[]

- Nope. 


- How long are names? I need to know to not over allocate space.

In [50]:
%sql select max(length(nameFirst)) as max_first_name, max(length(nameLast)) as max_last_name from people;

1 rows affected.


[(12, 14)]

In [48]:
%sql update people set nameFirst=NULL where nameFirst='';

37 rows affected.


[]

```
ALTER TABLE `lahman2019clean`.`people` 
CHANGE COLUMN `nameFirst` `nameFirst` VARCHAR(32) NULL DEFAULT NULL ,
CHANGE COLUMN `nameLast` `nameLast` VARCHAR(32) NOT NULL ;
```

### Enums

- Let's consider some of the other fields, i.e. ```bats``` and ```throws.```


- We can use another SQL construct: ```DISTINCT.``` This modifier eliminates duplicates in a result set.


- Let's look at a subset of rows to examine ```throws.```

In [51]:
%sql select throws from people limit 20;

20 rows affected.


[('R',),
 ('R',),
 ('R',),
 ('R',),
 ('L',),
 ('L',),
 ('R',),
 ('R',),
 ('R',),
 ('L',),
 ('R',),
 ('R',),
 ('R',),
 ('L',),
 ('L',),
 ('R',),
 ('L',),
 ('R',),
 ('R',),
 ('L',)]

- The result set has duplicate values, in this case the result is a table. Each row in the table has a single column. There are duplicate rows.


- What if I do not want duplicates? I can use the ```DISTINCT``` modifier.

In [11]:
x = %sql select distinct throws from lahman2019clean.people
print(list(x))

4 rows affected.
[('R',), ('L',), ('',), ('S',)]


- We have a little cleanup to do.
    - Git rid of ```Banana,``` which I added.
    - Deal with the ```''``` representation of "not known."

In [12]:
%sql update lahman2019clean.people set throws=NULL where throws='';

979 rows affected.


[]

- Now, let's make throws an ```ENUM.```

```
ALTER TABLE `lahman2019clean`.`people` 
CHANGE COLUMN `throws` `throws` ENUM('L', 'R', 'S') NULL DEFAULT NULL ;
```

### Dates

- There is a lot more "cleanup" that we can, and will, do for this table.


- We will do one more for now to demonstrate dates. We will focus on ```birthDate.```

In [14]:
%sql select count(*) from lahman2019clean.people where birthMonth='' or birthDay='' or birthYear=''

1 rows affected.


[(429,)]

- 429 entries for which we do not know some part of the birth date.


- How bad is this?

In [15]:
%sql select count(*) from lahman2019clean.people where  birthYear=''

1 rows affected.


[(120,)]

In [17]:
%sql select count(*) from lahman2019clean.people where  birthMonth=''

1 rows affected.


[(285,)]

In [19]:
%sql select count(*) from lahman2019clean.people where  birthDay=''

1 rows affected.


[(429,)]

In [16]:
%sql select count(*) from lahman2019clean.people where  birthYear='' and (birthMonth != '' or birthDay != '')

1 rows affected.


[(0,)]

In [20]:
%sql select count(*) from lahman2019clean.people where  birthMonth = '' and birthDay != ''

1 rows affected.


[(0,)]

In [21]:
%sql select count(*) from lahman2019clean.people where  birthYear!='' and birthMonth != '' and birthDay = ''

1 rows affected.


[(144,)]

- So,
    - Sometimes we have no information.
    - Sometimes we know only the year.
    - Sometimes we know the year and month.
    
    
- What do we want to do? We have to make a design choice. There are many options.
    - The ```birthDate``` is ```NULL``` if any part is NULL.
    - Approximate as well as we can:
        - If the ```birthMonth``` is ```NULL,``` we set it to ```January.```
        - If the ```birthDay``` is ```NULL,``` we set it to ```1.```
    - Create the ```birthDate``` if we can compute it, but keep the original data.
    - ... ...
    
    
- Some things are obvious.

In [23]:
%sql update lahman2019clean.people set birthYear=NULL where birthYear=''

120 rows affected.


[]

In [24]:
%sql update lahman2019clean.people set birthMonth=NULL where birthMonth=''

285 rows affected.


[]

In [25]:
%sql update lahman2019clean.people set birthDay=NULL where birthDay=''

429 rows affected.


[]

- There are a set of date and time functions. We can compute the birth date and death date as a date from the individual components. First, we need to clean up death info.

In [29]:
%%sql
update lahman2019clean.people set deathDay=NULL where deathDay='';
update lahman2019clean.people set deathMonth=NULL where deathMonth='';
update lahman2019clean.people set deathYear=NULL where deathYear='';

9970 rows affected.
9969 rows affected.
9968 rows affected.


[]

- Why where the numbers so much larger? Some people are not dead.


- Now, let's compute the information.

In [39]:
%%sql
SELECT
    playerid, nameLast, nameFirst,
	str_to_date(
		concat(birthYear,"-",birthMonth,"-",birthDay), "%Y-%m-%d"
    ) as DOB,
    str_to_date(
		concat(deathYear,"-",deathMonth,"-",deathDay), "%Y-%m-%d"
    ) as DOD
from lahman2019clean.people
limit 10;

10 rows affected.


[('aardsda01', 'Aardsma', 'David', datetime.date(1981, 12, 27), None),
 ('aaronha01', 'Aaron', 'Hank', datetime.date(1934, 2, 5), None),
 ('aaronto01', 'Aaron', 'Tommie', datetime.date(1939, 8, 5), datetime.date(1984, 8, 16)),
 ('aasedo01', 'Aase', 'Don', datetime.date(1954, 9, 8), None),
 ('abadan01', 'Abad', 'Andy', datetime.date(1972, 8, 25), None),
 ('abadfe01', 'Abad', 'Fernando', datetime.date(1985, 12, 17), None),
 ('abadijo01', 'Abadie', 'John', datetime.date(1850, 11, 4), datetime.date(1905, 5, 17)),
 ('abbated01', 'Abbaticchio', 'Ed', datetime.date(1877, 4, 15), datetime.date(1957, 1, 6)),
 ('abbeybe01', 'Abbey', 'Bert', datetime.date(1869, 11, 11), datetime.date(1962, 6, 11)),
 ('abbeych01', 'Abbey', 'Charlie', datetime.date(1866, 10, 14), datetime.date(1926, 4, 27))]

- These dates look kind of like strings. How do I know they are dates?


- "Which person for whom we have a death date lived the longest?"

In [40]:
%%sql
SELECT
    playerid, nameLast, nameFirst,
	str_to_date(
		concat(birthYear,"-",birthMonth,"-",birthDay), "%Y-%m-%d"
    ) as DOB,
    str_to_date(
		concat(deathYear,"-",deathMonth,"-",deathDay), "%Y-%m-%d"
    ) as DOD,
    datediff(
        str_to_date(
            concat(deathYear,"-",deathMonth,"-",deathDay), "%Y-%m-%d"
        ),
        str_to_date(
            concat(birthYear,"-",birthMonth,"-",birthDay), "%Y-%m-%d"
        )
    ) as lifespan_days,
    timestampdiff(
        YEAR,
        str_to_date(
            concat(birthYear,"-",birthMonth,"-",birthDay), "%Y-%m-%d"
        ),
        str_to_date(
            concat(deathYear,"-",deathMonth,"-",deathDay), "%Y-%m-%d"
        ) 
    ) as lifespan_years
FROM people
order by lifespan_days desc
limit 10;

10 rows affected.


[('hoffch01', 'Hoff', 'Red', datetime.date(1891, 5, 8), datetime.date(1998, 9, 17), 39213, 107),
 ('marreco01', 'Marrero', 'Connie', datetime.date(1911, 4, 25), datetime.date(2014, 4, 23), 37619, 102),
 ('wrighbo01', 'Wright', 'Bob', datetime.date(1891, 12, 13), datetime.date(1993, 7, 30), 37119, 101),
 ('parkeac01', 'Parker', 'Ace', datetime.date(1912, 5, 17), datetime.date(2013, 11, 6), 37063, 101),
 ('malinto01', 'Malinosky', 'Tony', datetime.date(1909, 10, 7), datetime.date(2011, 2, 8), 37014, 101),
 ('swanska01', 'Swanson', 'Karl', datetime.date(1900, 12, 17), datetime.date(2002, 4, 3), 36997, 101),
 ('daleyjo01', 'Daley', 'John', datetime.date(1887, 5, 25), datetime.date(1988, 8, 31), 36988, 101),
 ('otisbi01', 'Otis', 'Bill', datetime.date(1889, 12, 24), datetime.date(1990, 12, 15), 36880, 100),
 ('stilero01', 'Stiles', 'Rollie', datetime.date(1906, 11, 17), datetime.date(2007, 7, 22), 36772, 100),
 ('werbebi01', 'Werber', 'Billy', datetime.date(1908, 6, 20), datetime.date(2009, 1, 22), 36741, 100)]

- The key value of replace strings with the various date and time types, e.g. TIMESTAMP, DATETIME, is that you can perform date and time comparisons and math.

- OK. So how should I finalize the cleanup?
    - If I replace the three columns with a single ```DATETIME,``` I will have ```NULL``` for some people for which I have some partial information.
    - If I just update the table with a new column, I have duplicate data that could cause update errors. We need to make sure that applications consistently update two columns that depend on each other.
    
    
- It would be nice, if I could automatically _compute_ the date from the raw ```birthYear, birthMonth, birthDay``` but make it look like a column. We can.


```
ALTER TABLE `lahman2019clean`.`people` 
ADD COLUMN `birthDate` DATETIME GENERATED ALWAYS AS (str_to_date(
		concat(birthYear,"-",birthMonth,"-",birthDay), "%Y-%m-%d"
    )) AFTER `bbrefID`;
    
ALTER TABLE `lahman2019clean`.`people` 
ADD COLUMN `deathDate` DATETIME GENERATED ALWAYS AS (str_to_date(
		concat(deathYear,"-",deathMonth,"-",deathDay), "%Y-%m-%d"
    )) AFTER `birthDate`;
```

In [43]:
%%sql
select playerID, nameLast, nameFirst, birthDate, deathDate from lahman2019clean.people
limit 10;

10 rows affected.


[('aardsda01', 'Aardsma', 'David', datetime.date(1981, 12, 27), None),
 ('aaronha01', 'Aaron', 'Hank', datetime.date(1934, 2, 5), None),
 ('aaronto01', 'Aaron', 'Tommie', datetime.date(1939, 8, 5), datetime.datetime(1984, 8, 16, 0, 0)),
 ('aasedo01', 'Aase', 'Don', datetime.date(1954, 9, 8), None),
 ('abadan01', 'Abad', 'Andy', datetime.date(1972, 8, 25), None),
 ('abadfe01', 'Abad', 'Fernando', datetime.date(1985, 12, 17), None),
 ('abadijo01', 'Abadie', 'John', datetime.date(1850, 11, 4), datetime.datetime(1905, 5, 17, 0, 0)),
 ('abbated01', 'Abbaticchio', 'Ed', datetime.date(1877, 4, 15), datetime.datetime(1957, 1, 6, 0, 0)),
 ('abbeybe01', 'Abbey', 'Bert', datetime.date(1869, 11, 11), datetime.datetime(1962, 6, 11, 0, 0)),
 ('abbeych01', 'Abbey', 'Charlie', datetime.date(1866, 10, 14), datetime.datetime(1926, 4, 27, 0, 0))]

- I made the generated columns ```DATETIME``` just for the heck of it.


- I could use just the date part.

In [45]:
%%sql
select playerID, nameLast, nameFirst, date(birthDate) as birthJustDate, 
    date(deathDate) as justDeathDate from lahman2019clean.people
limit 10;

10 rows affected.


[('aardsda01', 'Aardsma', 'David', datetime.date(1981, 12, 27), None),
 ('aaronha01', 'Aaron', 'Hank', datetime.date(1934, 2, 5), None),
 ('aaronto01', 'Aaron', 'Tommie', datetime.date(1939, 8, 5), datetime.date(1984, 8, 16)),
 ('aasedo01', 'Aase', 'Don', datetime.date(1954, 9, 8), None),
 ('abadan01', 'Abad', 'Andy', datetime.date(1972, 8, 25), None),
 ('abadfe01', 'Abad', 'Fernando', datetime.date(1985, 12, 17), None),
 ('abadijo01', 'Abadie', 'John', datetime.date(1850, 11, 4), datetime.date(1905, 5, 17)),
 ('abbated01', 'Abbaticchio', 'Ed', datetime.date(1877, 4, 15), datetime.date(1957, 1, 6)),
 ('abbeybe01', 'Abbey', 'Bert', datetime.date(1869, 11, 11), datetime.date(1962, 6, 11)),
 ('abbeych01', 'Abbey', 'Charlie', datetime.date(1866, 10, 14), datetime.date(1926, 4, 27))]

- I could have used the ```DATE()``` function in the generated statement.


- There are two types of generated columns:
    - __Virtual__ is computed on demand when requested in a SQL statement.
    - __Stored__ is, well stored, and changed when the base fields change.

### People Cleanup Summary

- We just touched on some of the data cleanse and refactoring that we could have done on people.


- We will do additional cleanup examples as we progress through the semester.

# Some Multi-Table SQL

## Concept

- Our hypothetical application scenario requires information about players and players' performance. We want to be able to display summaries that fans and fantasy players can browse and query.


- Do we have any idea what this information might be? What do people want to see through our web UI?


- Web application and most projects define _use cases_ and/or _user stories._ 
    - [Use case:](https://en.wikipedia.org/wiki/Use_case) "In software and systems engineering, a use case is a list of actions or event steps typically defining the interactions between a role (known in the Unified Modeling Language as an actor) and a system to achieve a goal." 
    - [User story:](https://en.wikipedia.org/wiki/User_story) "In software development and product management, a user story is an informal, natural language description of one or more features of a software system. User stories are often written from the perspective of an end user or user of a system."
    
    
- Identifying and prioritizing use cases/user stories is a complex part of [software product management](https://en.wikipedia.org/wiki/Software_product_management).


- We will pretend we have some user stories.


- Where am I going to get the initial user stories? People used to/still do collect [baseball cards](https://en.wikipedia.org/wiki/Baseball_card).


| <img src="../../images/baseball_cards.jpeg"> |
| :---: |
| __Baseball Card Collections__ |


- Why did kids collect baseball cards?
    - We did not have XBox, PlayStation, etc.
    - There was no Internet or web.
    - We had five television channels.
    - Baseball cards came with bubblegum.


- We had a lot of time. I used catch bees in the summer and falling leaves in the fall, for example.


- [Topps Company, Inc.:](https://en.wikipedia.org/wiki/Topps)
    - "The Topps Company, Inc., manufactures chewing gum, candy, and collectibles. Based in New York City,[1] Topps is best known as a leading producer of basketball cards, American football cards, baseball cards, hockey cards, association football cards, and other sports and non-sports themed trading cards. It is currently the only baseball card manufacturer with a contract with Major League Baseball."
    - 2006 revenue was \$317 million.

- What kind of stuff is on a baseball card?

| <img src="../../images/baseball_card_back.jpeg"> |
| :---: |
| __Baseball Card Data__ |


- There is a summary of information:
    - Personal information.
    - Appearances, i.e. games played.
    - Batting performance, if any.
    - Pitching performance, if any.
    - Fielding performance, if any.
    
    
- We have imported ```appearances``` and ```batting.``` We need to import ```pitching``` and ```fielding.```


- We then need to figure out how to relate this data. I am going to do both of these things for you.
    

## Primary Keys

- The primary keys are:
    - Pitching: ```playerID, teamID, yearID, stint```
    - Fielding: ```playerID, teamID, yearID, stint, POS```
    
    
- How did I know that ```fielding``` also needs ```POS```?

In [49]:
%%sql
SELECT count(*) as count, playerid, teamid, yearid, stint FROM lahman2019raw.fielding 
	group by playerid, teamid, yearid, stint order by count desc limit 10;

10 rows affected.


[(7, 'rominan01', 'DET', '2017', '1'),
 (7, 'clarksp01', 'BFP', '1890', '1'),
 (7, 'gettich01', 'NY1', '1898', '1'),
 (7, 'elmorja01', 'HOU', '2013', '1'),
 (7, 'tovarce01', 'MIN', '1968', '1'),
 (7, 'sheldsc01', 'TEX', '2000', '1'),
 (7, 'mcallsp01', 'CL4', '1899', '1'),
 (7, 'mertesa01', 'CHA', '1902', '1'),
 (7, 'kellyki01', 'CHN', '1884', '1'),
 (7, 'haltesh01', 'DET', '2000', '1')]

- What does this mean? Baseball uses integers 1 to 9 to represent fielding positions.

| <img src="../../images/Baseball_positions.jpg"> |
| :---: |
| __Baseball Positions__ |


- Here is another interesting query.

In [51]:
%%sql
select playerid, teamid, yearid, stint, pos from lahman2019raw.fielding
where playerid='rominan01' and yearid='2017' and teamid='DET' and stint='1';

7 rows affected.


[('rominan01', 'DET', '2017', '1', '1B'),
 ('rominan01', 'DET', '2017', '1', '2B'),
 ('rominan01', 'DET', '2017', '1', '3B'),
 ('rominan01', 'DET', '2017', '1', 'C'),
 ('rominan01', 'DET', '2017', '1', 'OF'),
 ('rominan01', 'DET', '2017', '1', 'P'),
 ('rominan01', 'DET', '2017', '1', 'SS')]

- So, I am going to change the fields from texts to types, and set up the keys. 

```
ALTER TABLE `lahman2019clean`.`fielding` 
CHANGE COLUMN `playerID` `playerID` VARCHAR(12) NOT NULL ,
CHANGE COLUMN `yearID` `yearID` VARCHAR(4) NOT NULL ,
CHANGE COLUMN `stint` `stint` VARCHAR(12) NOT NULL ,
CHANGE COLUMN `teamID` `teamID` VARCHAR(4) NOT NULL ,
CHANGE COLUMN `POS` `POS` VARCHAR(2) NOT NULL ,
ADD PRIMARY KEY (`playerID`, `teamID`, `yearID`, `stint`, `POS`);


ALTER TABLE `lahman2019clean`.`pitching` 
CHANGE COLUMN `playerID` `playerID` VARCHAR(12) NOT NULL ,
CHANGE COLUMN `yearID` `yearID` VARCHAR(4) NOT NULL ,
CHANGE COLUMN `stint` `stint` VARCHAR(2) NOT NULL ,
CHANGE COLUMN `teamID` `teamID` VARCHAR(4) NOT NULL ,
ADD PRIMARY KEY (`playerID`, `teamID`, `yearID`, `stint`);

```

- That was pretty straightforward.

## Relationships

- How do these tables relate? Figuring this out will give us some practice with more advanced SQL query capabilities.


- Are there ```appearance``` records for which there is no corresponding ```people``` entry, or vice-versa?

In [55]:
%%sql
select count(*) as non_appearances from lahman2019clean.people
    where
        not exists
            (select * from lahman2019clean.appearances where lahman2019clean.appearances.playerid
                 =
                 lahman2019clean.people.playerid)

1 rows affected.


[(189,)]

- This is demonstrating two (or several) concepts that we will explore more deeply.


- __Exists__

<hr style="height:2px;">

| <img src="../../images/slide_3_44.jpeg"> |
| :---: |
| __Exists Operation__ |

<hr style="height:2px;">

<hr style="height:2px;">

| <img src="../../images/slide_3_45.jpeg"> |
| :---: |
| __Exists and Subqueries |

<hr style="height:2px;">


- The _Section_ table.

In [2]:
%sql select * from newdbbook.section limit 10;

10 rows affected.


[('105', '1', 'Fall', Decimal('2009'), 'Chandler', '375', 'C'),
 ('105', '2', 'Fall', Decimal('2002'), 'Taylor', '183', 'C'),
 ('137', '1', 'Spring', Decimal('2002'), 'Fairchild', '145', 'I'),
 ('158', '1', 'Fall', Decimal('2008'), 'Whitman', '434', 'F'),
 ('158', '2', 'Spring', Decimal('2008'), 'Taylor', '812', 'D'),
 ('169', '1', 'Spring', Decimal('2007'), 'Gates', '314', 'A'),
 ('169', '2', 'Fall', Decimal('2002'), 'Drown', '757', 'L'),
 ('192', '1', 'Fall', Decimal('2002'), 'Polya', '808', 'B'),
 ('200', '1', 'Spring', Decimal('2007'), 'Saucon', '180', 'D'),
 ('200', '2', 'Fall', Decimal('2002'), 'Chandler', '375', 'D')]

- The example query.

In [3]:
%%sql
use newdbbook;
select course_id from section as s
    where semester='Fall' and year=2017 and
    exists
        (select * from section as T
            where semester='Spring' and year=2018 and
                s.course_id=t.course_id)

0 rows affected.
0 rows affected.


[]

- That was anti-climactic. Lets' try something else. Which people have been both players and managers.

In [13]:
%%sql
use lahman2019raw;
select playerID, nameLast, nameFirst from people as players
    where exists (select * from managers
                  where players.playerid = managers.playerid)
limit 10;

0 rows affected.
10 rows affected.


[('actama99', 'Acta', 'Manny'),
 ('adairbi99', 'Adair', 'Bill'),
 ('adcocjo01', 'Adcock', 'Joe'),
 ('addybo01', 'Addy', 'Bob'),
 ('allenbo01', 'Allen', 'Bob'),
 ('allisdo01', 'Allison', 'Doug'),
 ('alomasa02', 'Alomar', 'Sandy'),
 ('aloufe01', 'Alou', 'Felipe'),
 ('alstowa01', 'Alston', 'Walter'),
 ('altobjo01', 'Altobelli', 'Joe')]

## Back to Relationships

- There are people who never appeared. Actually, there are 189.

In [24]:
%sql use lahman2019clean;

0 rows affected.


[]

In [30]:
no_of_non_players = %sql \
    select count(*) as count from people \
        where not exists (select * from appearances where \
                          appearances.playerid=people.playerid)

1 rows affected.


In [31]:
no_of_non_players              

[(189,)]

- What about the other way around?

In [38]:
no_of_non_people = %sql select count(*) as count from appearances where not exists (select * from people where \
                        appearances.playerid=people.playerid);

1 rows affected.


In [39]:
no_of_non_people

[(1,)]

- Huh? Who is this imaginary man?

In [35]:
%sql select playerid from appearances where not exists (select * from people where \
                        appearances.playerid=people.playerid);

1 rows affected.


[('thompan01',)]

- How many entries are there in people?

In [43]:
no_of_people = %sql select count(*) as count from people;
no_of_people

1 rows affected.


[(19617,)]

- How many distinct playerids are in appearances?

In [37]:
no_of_people_appeared = %sql select count(*) as count from \
    (select distinct playerid from appearances) as a;
no_of_people_appeared

1 rows affected.


[(19429,)]

- Some sanity checking

In [44]:
# Number of people we know about - number of distinct players in appearances - number of people who did not appear
no_of_people[0]['count'] - no_of_non_players[0]['count'] - no_of_people_appeared[0]['count']

-1

- That should be zero.

In [45]:
%sql select * from appearances where not exists (select * from people where \
                        appearances.playerid=people.playerid);

1 rows affected.


[('1875', 'WS6', 'NA', 'thompan01', '11', '', '11', '', '0', '11', '0', '0', '0', '0', '0', '0', '1', '1', '0', '', '')]

- That MUST be an error. 104K entries and 19K distinct ```playerIDs``` and ONLY one from a log time ago is off.


- Let's fix it.

In [46]:
%%sql
insert into people (playerid, nameLast, nameFirst)
    select playerID, 'UNKNOWN', 'UNKNOWN' from appearances
        where
            not exists (select * from people where appearances.playerid=people.playerid);

1 rows affected.


[]

- We can now state our first __foreign key__ integrity constraint.
    - For every entry in appearances.
    - There MUST be an entry in people with the playerID in the appearances row.
    
<hr style="height:2px;">

| <img src="../../images/slide_2_7.jpeg"> |
| :---: |
| __Keys and Foreign Keys__ |

<hr style="height:2px;">

<hr style="height:2px;">

| <img src="../../images/slide_4_40.jpeg"> |
| :---: |
| __Referential Integrity__ |

<hr style="height:2px;">

- Now we can add the constraint.

```
ALTER TABLE `lahman2019clean`.`appearances` 
ADD CONSTRAINT `a_to_p`
  FOREIGN KEY (`playerID`)
  REFERENCES `lahman2019clean`.`people` (`playerID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

```

<hr style="height:2px;">

| <img src="../../images/slide_4_41.jpeg"> |
| :---: |
| __Referential Integrity__ |

<hr style="height:2px;">

<hr style="height:2px;">

| <img src="../../images/slide_4_42.jpeg"> |
| :---: |
| __Cascading Referential Integrity__ |

<hr style="height:2px;">


- I never use cascading.

- A couple of tests.

In [52]:
import pymysql
default_cnx = pymysql.connect(host='localhost',
                             user='root',
                             password='dbuserdbuser',
                             db='lahman2019clean',
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor)

In [53]:
sql = "delete from people where playerid=%s"
try:
    cur = default_cnx.cursor()
    res = cur.execute(sql, ('willite01'))
    print("We deleted Ted Williams")
except Exception as e:
    print("Exception = ", e)

Exception =  (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`lahman2019clean`.`appearances`, CONSTRAINT `a_to_p` FOREIGN KEY (`playerID`) REFERENCES `people` (`playerID`))')


- With a little more exploration, we can identify and document some additional referential integrity constraints.
    - $batting \rightarrow appearances$
    - $fielding \rightarrow appearances$  (there are two missing entries)
    - $pitching \rightarrow appearances$
    - $managers \rightarrow people$
    - $managers \rightarrow teams$
    - $appearances \rightarrow teams$
    
    
- The query to cleanup fielding/appearances is

```
insert into appearances (playerid, teamid, yearid)
	 select distinct playerid, teamid, yearid from fielding where
	not exists (select * from appearances
		where appearances.playerid=fielding.playerid and appearances.teamid=fielding.teamid
			and appearances.yearid=fielding.yearid);
```

- The reverse engineered data (ER) model for the changes we have made is:

<hr style="height:2px;">

| <img src="../../images/lahmancleanri.jpeg"> |
| :---: |
| __Referential Integrity__ |

<hr style="height:2px;">

- I was on airplane when I did this. So, if I got it right, it is a miracle.


- We have done some very basic cleanup and reverse engineering, and we will do more as the semester continues.

# Some Modeling Concepts

## Entity-Relationship Modeling/Diagrams


__Note:__ Ramakrishana and Gehrke sections 2.1-2.7 cover E-R modeling and conceptual design a different, more powerful and complex notation. I am going to use a simple notation, "Crow's Foot Notation." There is a [good online, introductory tutorial.](http://www.vertabelo.com/blog/technical-articles/crow-s-foot-notation)


## Overview

"An entity–relationship model (ER model for short) describes interrelated things of interest in a specific domain of knowledge. A basic ER model is composed of entity types (which classify the things of interest) and specifies relationships that can exist between instances of those entity types.


An entity–relationship diagram for an MMORPG using Chen's notation.
In software engineering, an ER model is commonly formed to represent things that a business needs to remember in order to perform business processes. Consequently, the ER model becomes an abstract data model, that defines a data or information structure which can be implemented in a database, typically a relational database." (https://en.wikipedia.org/wiki/Entity%E2%80%93relationship_model)

| <img src="../../images/conceptuallogicalphysical.jpeg" width="90%"> |
| :---: |
| __Conceptual, Logical and Physical Design (Models)__ |

- There are some patterns or ways to think about entities:
    - A _Strong Entity_ is independent from other entities, and are often called parent entities, since they will often have weak entities that depend on them. They will also have a primary key, distinguishing each occurrence of the entity.
    - A _Weak Entity_ depend on some other entity type (for existence). They don't have (independent) primary keys, and have no meaning in the diagram without their parent entity.
    - An _Associative Entity_ relates the instances of several entity types. They also contain attributes specific to the association.
    
## Crow's Foot Notation Symbols

| <img src="../../images/crows_foot_notation.jpeg"> |
| :---: |
| [Crow's Foot Notation](https://www.vivekmchawla.com/erd-crows-foot-relationship-symbols-cheat-sheet/) |

- If you reverse engineer a MySQL database, you get a Crow's Foot physical model. This is an example from the MySQL Sakila sample database.

| <img src="../../images/sakila_full_database_schema_diagram.png" > |
| :---: |
| __Sakila Sample Database Diagram__ |


# More Fun with Multiple Tables

## Concept

- Remember the baseball card and the concept of player performance summary?

| <img src="../../images/baseball_card_back.jpeg"> |
| :---: |
| __Baseball Card Data__ |

- The yearly performance information looks like "one table" but seems to have data from "two tables:" 1) Appearances, 2) Batting.


- How does this work? This is a __join.__

In [100]:
%%sql
use lahman2019clean;

select
    appearances.playerid, appearances.playerid, appearances.teamid, appearances.yearid,
    appearances.g_all as games, appearances.gs as games_started,
    batting.ab, batting.h, batting.`2b`, batting.`3b`, batting.hr, batting.rbi, batting.bb
from appearances join batting
on
    appearances.playerid=batting.playerid and
    appearances.teamid=batting.teamid and
    appearances.yearid = batting.yearid
where appearances.playerid='willite01';

0 rows affected.
19 rows affected.


[('willite01', 'willite01', 'BOS', '1939', '149', '149', '565', '185', '44', '11', '31', '145', '107'),
 ('willite01', 'willite01', 'BOS', '1940', '144', '143', '561', '193', '43', '14', '23', '113', '96'),
 ('willite01', 'willite01', 'BOS', '1941', '143', '133', '456', '185', '33', '3', '37', '120', '147'),
 ('willite01', 'willite01', 'BOS', '1942', '150', '150', '522', '186', '34', '5', '36', '137', '145'),
 ('willite01', 'willite01', 'BOS', '1946', '150', '150', '514', '176', '37', '8', '38', '123', '156'),
 ('willite01', 'willite01', 'BOS', '1947', '156', '156', '528', '181', '40', '9', '32', '114', '162'),
 ('willite01', 'willite01', 'BOS', '1948', '137', '134', '509', '188', '44', '3', '25', '127', '126'),
 ('willite01', 'willite01', 'BOS', '1949', '155', '155', '566', '194', '39', '3', '43', '159', '162'),
 ('willite01', 'willite01', 'BOS', '1950', '89', '86', '334', '106', '24', '1', '28', '97', '82'),
 ('willite01', 'willite01', 'BOS', '1951', '148', '147', '531', '169', '28', '4', '30', '126', '144'),
 ('willite01', 'willite01', 'BOS', '1952', '6', '2', '10', '4', '0', '1', '1', '3', '2'),
 ('willite01', 'willite01', 'BOS', '1953', '37', '26', '91', '37', '6', '0', '13', '34', '19'),
 ('willite01', 'willite01', 'BOS', '1954', '117', '113', '386', '133', '23', '1', '29', '89', '136'),
 ('willite01', 'willite01', 'BOS', '1955', '98', '93', '320', '114', '21', '3', '28', '83', '91'),
 ('willite01', 'willite01', 'BOS', '1956', '136', '110', '400', '138', '28', '2', '24', '82', '102'),
 ('willite01', 'willite01', 'BOS', '1957', '132', '125', '420', '163', '28', '1', '38', '87', '119'),
 ('willite01', 'willite01', 'BOS', '1958', '129', '114', '411', '135', '23', '2', '26', '85', '98'),
 ('willite01', 'willite01', 'BOS', '1959', '103', '75', '272', '69', '15', '0', '10', '43', '52'),
 ('willite01', 'willite01', 'BOS', '1960', '113', '87', '310', '98', '15', '0', '29', '72', '75')]

<hr style="height:2px;">

| <img src="../../images/slide_4_3.jpeg"> |
| :---: |
| __JOIN__ |

<hr style="height:2px;">

__Note:__ We will cover the different types of join in a future lecture.

- The query is correct for Ted Williams, but would not be correct for someone who had multiple stints in a single season.

In [60]:
%%sql

select playerid, teamid, yearid, count(*) as count from batting where teamid='BOS'
	group by playerid, teamid, yearid order by count desc limit 10;

10 rows affected.


[('mantoje01', 'BOS', '1996', 2),
 ('wallmu01', 'BOS', '1959', 2),
 ('linch01', 'BOS', '2012', 1),
 ('mortecl01', 'BOS', '2012', 1),
 ('repkoja01', 'BOS', '2012', 1),
 ('thomaju01', 'BOS', '2012', 1),
 ('bogaexa01', 'BOS', '2013', 1),
 ('delatjo01', 'BOS', '2013', 1),
 ('holtbr01', 'BOS', '2013', 1),
 ('moralfr01', 'BOS', '2013', 1)]

- What are the implications of the stints on the join result.

In [65]:
%%sql

select
    appearances.playerid, appearances.teamid, appearances.yearid,
    appearances.g_all as games, appearances.gs as games_started,
    batting.ab, batting.h, batting.`2b`, batting.`3b`, batting.hr, batting.rbi, batting.bb
from appearances join batting
on
    appearances.playerid=batting.playerid and
    appearances.teamid=batting.teamid and
    appearances.yearid = batting.yearid
where appearances.playerid='mantoje01' and appearances.yearid='1996';

3 rows affected.


[('mantoje01', 'BOS', '1996', '22', '13', '30', '8', '3', '1', '2', '4', '3'),
 ('mantoje01', 'BOS', '1996', '22', '13', '18', '2', '0', '0', '0', '2', '5'),
 ('mantoje01', 'SEA', '1996', '21', '15', '54', '10', '3', '0', '1', '4', '9')]

- A single appearance rows matches two batting records. What want want to do first is to _compress_ or _group_ multiple batting rows with the same teamid and yearid into a single, aggregate row.

In [68]:
%%sql

select playerid, sum(batting.ab) as ab, sum(batting.h) as h, 
    sum(batting.`2b`) as `2b`, sum(batting.`3b`) as `3b`, sum(batting.hr) as hr,
        sum(batting.rbi) as rbi, sum(batting.bb) as bb
    from
        batting
        where playerid='mantoje01' and yearid='1996'
        group by playerid, teamid, yearid
      

2 rows affected.


[('mantoje01', 48.0, 10.0, 3.0, 1.0, 2.0, 6.0, 8.0),
 ('mantoje01', 54.0, 10.0, 3.0, 0.0, 1.0, 4.0, 9.0)]

<hr style="height:2px;">

| <img src="../../images/slide_3_30.jpeg"> |
| :---: |
| __Aggregate Functions__ |

<hr style="height:2px;">

- You have seen me do this several times with the count() function.

<hr style="height:2px;">

| <img src="../../images/slide_3_31.jpeg"> |
| :---: |
| __Aggregate Functions__ |

In [71]:
%%sql

select * from newdbbook.instructor where dept_name='Comp. Sci.'

2 rows affected.


[('3335', 'Bourrier', 'Comp. Sci.', Decimal('80797.83')),
 ('34175', 'Bondi', 'Comp. Sci.', Decimal('115469.11'))]

In [76]:
%sql select avg(salary) from newdbbook.instructor where dept_name='Comp. Sci.'

1 rows affected.


[(Decimal('98133.470000'),)]

In [78]:
%sql select round(avg(salary), 2) as avg_salary from newdbbook.instructor where dept_name='Comp. Sci.'

1 rows affected.


[(Decimal('98133.47'),)]

<hr style="height:2px;">

| <img src="../../images/slide_3_32.jpeg"> |
| :---: |
| __Aggregate Functions__ |

<hr style="height:2px;">

- We now have all of the tools we need to compute player (batting) performance summary.


- The same for fielding, pitching, etc.

In [86]:
%%sql 

select appearances.playerid, appearances.teamid, appearances.yearid,
        appearances.g_all as games, appearances.gs as games_started,
        batting_all.ab, batting_all.h,  batting_all.`3b`, batting_all.hr,
        batting_all.rbi, batting_all.bb
from
    appearances
join
    (select playerid, teamid, yearid, sum(ab) as ab, sum(h) as h, 
        sum(`2b`) as `2b`, sum(`3b`) as `3b`, sum(hr) as hr,
            sum(rbi) as rbi, sum(bb) as bb
        from
            batting
            group by playerid, teamid, yearid) as batting_all
on
    appearances.playerid=batting_all.playerid and
    appearances.teamid=batting_all.teamid and
    appearances.yearid=batting_all.yearid
where
    appearances.playerid='willite01';

19 rows affected.


[('willite01', 'BOS', '1939', '149', '149', 565.0, 185.0, 11.0, 31.0, 145.0, 107.0),
 ('willite01', 'BOS', '1940', '144', '143', 561.0, 193.0, 14.0, 23.0, 113.0, 96.0),
 ('willite01', 'BOS', '1941', '143', '133', 456.0, 185.0, 3.0, 37.0, 120.0, 147.0),
 ('willite01', 'BOS', '1942', '150', '150', 522.0, 186.0, 5.0, 36.0, 137.0, 145.0),
 ('willite01', 'BOS', '1946', '150', '150', 514.0, 176.0, 8.0, 38.0, 123.0, 156.0),
 ('willite01', 'BOS', '1947', '156', '156', 528.0, 181.0, 9.0, 32.0, 114.0, 162.0),
 ('willite01', 'BOS', '1948', '137', '134', 509.0, 188.0, 3.0, 25.0, 127.0, 126.0),
 ('willite01', 'BOS', '1949', '155', '155', 566.0, 194.0, 3.0, 43.0, 159.0, 162.0),
 ('willite01', 'BOS', '1950', '89', '86', 334.0, 106.0, 1.0, 28.0, 97.0, 82.0),
 ('willite01', 'BOS', '1951', '148', '147', 531.0, 169.0, 4.0, 30.0, 126.0, 144.0),
 ('willite01', 'BOS', '1952', '6', '2', 10.0, 4.0, 1.0, 1.0, 3.0, 2.0),
 ('willite01', 'BOS', '1953', '37', '26', 91.0, 37.0, 0.0, 13.0, 34.0, 19.0),
 ('willite01', 'BOS', '1954', '117', '113', 386.0, 133.0, 1.0, 29.0, 89.0, 136.0),
 ('willite01', 'BOS', '1955', '98', '93', 320.0, 114.0, 3.0, 28.0, 83.0, 91.0),
 ('willite01', 'BOS', '1956', '136', '110', 400.0, 138.0, 2.0, 24.0, 82.0, 102.0),
 ('willite01', 'BOS', '1957', '132', '125', 420.0, 163.0, 1.0, 38.0, 87.0, 119.0),
 ('willite01', 'BOS', '1958', '129', '114', 411.0, 135.0, 2.0, 26.0, 85.0, 98.0),
 ('willite01', 'BOS', '1959', '103', '75', 272.0, 69.0, 0.0, 10.0, 43.0, 52.0),
 ('willite01', 'BOS', '1960', '113', '87', 310.0, 98.0, 0.0, 29.0, 72.0, 75.0)]

- If we wanted to be really cool and really helpful, we could throw in some computed metrics that are common in baseball.

In [91]:
%%sql

select appearances.playerid, appearances.teamid, appearances.yearid,
        appearances.g_all as games, appearances.gs as games_started,
        batting_all.ab, batting_all.h,  batting_all.`3b`, batting_all.hr,
        batting_all.rbi, batting_all.bb, avg, obp
from
    appearances
join
    (select playerid, teamid, yearid, sum(ab) as ab, sum(h) as h, 
        sum(`2b`) as `2b`, sum(`3b`) as `3b`, sum(hr) as hr,
            sum(rbi) as rbi, sum(bb) as bb,
             round(sum(h)/nullif(sum(ab),0),3) as avg,
             round(sum(h+bb)/nullif(sum(ab + bb),0),3) as obp
        from
            batting
            group by playerid, teamid, yearid) as batting_all
on
    appearances.playerid=batting_all.playerid and
    appearances.teamid=batting_all.teamid and
    appearances.yearid=batting_all.yearid
where
    appearances.playerid='willite01';

19 rows affected.


[('willite01', 'BOS', '1939', '149', '149', 565.0, 185.0, 11.0, 31.0, 145.0, 107.0, 0.327, 0.435),
 ('willite01', 'BOS', '1940', '144', '143', 561.0, 193.0, 14.0, 23.0, 113.0, 96.0, 0.344, 0.44),
 ('willite01', 'BOS', '1941', '143', '133', 456.0, 185.0, 3.0, 37.0, 120.0, 147.0, 0.406, 0.551),
 ('willite01', 'BOS', '1942', '150', '150', 522.0, 186.0, 5.0, 36.0, 137.0, 145.0, 0.356, 0.496),
 ('willite01', 'BOS', '1946', '150', '150', 514.0, 176.0, 8.0, 38.0, 123.0, 156.0, 0.342, 0.496),
 ('willite01', 'BOS', '1947', '156', '156', 528.0, 181.0, 9.0, 32.0, 114.0, 162.0, 0.343, 0.497),
 ('willite01', 'BOS', '1948', '137', '134', 509.0, 188.0, 3.0, 25.0, 127.0, 126.0, 0.369, 0.494),
 ('willite01', 'BOS', '1949', '155', '155', 566.0, 194.0, 3.0, 43.0, 159.0, 162.0, 0.343, 0.489),
 ('willite01', 'BOS', '1950', '89', '86', 334.0, 106.0, 1.0, 28.0, 97.0, 82.0, 0.317, 0.452),
 ('willite01', 'BOS', '1951', '148', '147', 531.0, 169.0, 4.0, 30.0, 126.0, 144.0, 0.318, 0.464),
 ('willite01', 'BOS', '1952', '6', '2', 10.0, 4.0, 1.0, 1.0, 3.0, 2.0, 0.4, 0.5),
 ('willite01', 'BOS', '1953', '37', '26', 91.0, 37.0, 0.0, 13.0, 34.0, 19.0, 0.407, 0.509),
 ('willite01', 'BOS', '1954', '117', '113', 386.0, 133.0, 1.0, 29.0, 89.0, 136.0, 0.345, 0.515),
 ('willite01', 'BOS', '1955', '98', '93', 320.0, 114.0, 3.0, 28.0, 83.0, 91.0, 0.356, 0.499),
 ('willite01', 'BOS', '1956', '136', '110', 400.0, 138.0, 2.0, 24.0, 82.0, 102.0, 0.345, 0.478),
 ('willite01', 'BOS', '1957', '132', '125', 420.0, 163.0, 1.0, 38.0, 87.0, 119.0, 0.388, 0.523),
 ('willite01', 'BOS', '1958', '129', '114', 411.0, 135.0, 2.0, 26.0, 85.0, 98.0, 0.328, 0.458),
 ('willite01', 'BOS', '1959', '103', '75', 272.0, 69.0, 0.0, 10.0, 43.0, 52.0, 0.254, 0.373),
 ('willite01', 'BOS', '1960', '113', '87', 310.0, 98.0, 0.0, 29.0, 72.0, 75.0, 0.316, 0.449)]

- There are some useful functions in the computations:
    - ```round()```
    - ```nullif()``` used to prevent divide by zero.

# REST Implementation

## Concept

- "Representational state transfer (REST) is a software architectural style that defines a set of constraints to be used for creating Web services. Web services that conform to the REST architectural style, called RESTful Web services (RWS), provide interoperability between computer systems on the Internet. RESTful Web services allow the requesting systems to access and manipulate textual representations of Web resources by using a uniform and predefined set of stateless operations.
<br>
... ...
<br>
Web resources" were first defined on the World Wide Web as documents or files identified by their URLs. However, today they have a much more generic and abstract definition that encompasses every thing or entity that can be identified, named, addressed, or handled, in any way whatsoever, on the Web." (https://en.wikipedia.org/wiki/Representational_state_transfer)


- You can think of the web as a "worldwide database." Sometimes the returned data format is what a browser understands:
    - HTML
    - CSS
    - JPB
    - etc.
    

- Other times, calls return a format that programs understand. This is just another kind of database.

In [54]:
%sql select * from lahman2019clean.people where nameLast='Williams' and birthCity='San Diego'

2 rows affected.


[('willite01', '1918', '8', '30', 'USA', 'CA', 'San Diego', '2002', '7', '5', 'USA', 'FL', 'Inverness', 'Ted', 'Williams', 'Theodore Samuel', 205, '75', 'L', 'R', '1939-04-20', '1960-09-28', 'willt103', 'willite01'),
 ('willitr01', '1992', '4', '25', 'USA', 'CA', 'San Diego', '', '', '', '', '', '', 'Trevor', 'Williams', 'Trevor Anthony', 230, '75', 'R', 'R', '2016-09-07', '2018-09-27', 'willt002', 'willitr01')]

- What is an equivalent query that a REST application endpoint might implement?

In [92]:
%load_ext restmagic
%rest http://127.0.0.1:5000/api/lahman2019clean/people?nameLast=williams&birthCity=San%20Diego

{
  "data": [
    {
      "playerID": {
        "value": "willite01",
        "link": {
          "rel": "people",
          "href": "/api/people/willite01"
        }
      },
      "birthYear": "1918",
      "birthMonth": "8",
      "birthDay": "30",
      "birthCountry": "USA",
      "birthState": "CA",
      "birthCity": "San Diego",
      "deathYear": "2002",
      "deathMonth": "7",
      "deathDay": "5",
      "deathCountry": "USA",
      "deathState": "FL",
      "deathCity": "Inverness",
      "nameFirst": "Ted",
      "nameLast": "Williams",
      "nameGiven": "Theodore Samuel",
      "weight": 205,
      "height": "75",
      "bats": "L",
      "throws": "R",
      "debut": "1939-04-20",
      "finalGame": "1960-09-28",
      "retroID": "willt103",
      "bbrefID": "willite01",
      "birthDate": "1918-08-30 00:00:00",
      "deathDate": "2002-07-05 00:00:00",
      "appearances": [
        {
          "yearID": "1939",
          "teamID": "BOS",
          "lgID": "AL",
     

<Response [200]>

## Resource

<hr style="height:2px;">

| <img src="../../images/rest_concepts.png"> |
| :---: |
| [Resource Concept](https://restful-api-design.readthedocs.io/en/latest/resources.html) |

<hr style="height:2px;">

"The fundamental concept in any RESTful API is the resource. A resource is an object with a type, associated data, relationships to other resources, and a set of methods that operate on it. It is similar to an object instance in an object-oriented programming language, with the important difference that only a few standard methods are defined for the resource (corresponding to the standard HTTP GET, POST, PUT and DELETE methods), while an object instance typically has many methods.

Resources can be grouped into collections. Each collection is homogeneous so that it contains only one type of resource, and unordered. Resources can also exist outside any collection. In this case, we refer to these resources as singleton resources. Collections are themselves resources as well.

Collections can exist globally, at the top level of an API, but can also be contained inside a single resource. In the latter case, we refer to these collections as sub-collections. Sub-collections are usually used to express some kind of “contained in” relationship. We go into more detail on this in Relationships." (https://restful-api-design.readthedocs.io/en/latest/resources.html)

- Simplistic mapping to relational/SQL
    - Collection is a table.
    - Resource is a row/tuple.
    - Sub-resource is a _dependent entity_ (aka _weak entity._)
    - Sub-resource collection is the set of dependent entities that are dependent on/contained by the containing resource.
    
"In a relational database, a weak entity is an entity that cannot be uniquely identified by its attributes alone; therefore, it must use a foreign key in conjunction with its attributes to create a primary key. The foreign key is typically a primary key of an entity it is related to." (https://en.wikipedia.org/wiki/Weak_entity)

| <img src="../../images/orders_weak.jpeg"> |
| :---: |
| __Relationships__ |

- In the [classic cars database example:](http://www.mysqltutorial.org/mysql-sample-database.aspx)
    - _orderdetails_ is a dependent/weak entity/sub-resource that _orders_ logically contains.
    - The relationship is different than the relationship between _customers_ and _orders_ or _orderdetails_ and _products._

<hr style="height:2px;">

| <img src="../../images/order_form.jpeg"> |
| :---: |
| __Sub-Resources and Linked Resources__ |

<hr style="height:2px;">

- Simple way to think about it:
    - If I delete the _order,_ the _orderdetails_ is also deleted.
    - I can find the _customer_ and _product_ from _orders_ and _ordersdetails,_ but deleting the _order_ does not effect their existence.

- How does someone access the information when surfaced through a REST API?

In [93]:
%rest http://127.0.0.1:5000/api/classicmodels/customers

{
  "data": [
    {
      "customerNumber": 103,
      "customerName": "Atelier graphique",
      "contactLastName": "Schmitt",
      "contactFirstName": "Carine ",
      "phone": "40.32.2555",
      "addressLine1": "54, rue Royale",
      "addressLine2": null,
      "city": "Nantes",
      "state": null,
      "postalCode": "44000",
      "country": "France",
      "salesRepEmployeeNumber": 1370,
      "creditLimit": "21000.00",
      "payments": [
        {
          "customerNumber": 103,
          "checkNumber": "HQ336336",
          "paymentDate": "2004-10-19",
          "amount": "6066.78"
        },
        {
          "customerNumber": 103,
          "checkNumber": "JM555205",
          "paymentDate": "2003-06-05",
          "amount": "14571.44"
        },
        {
          "customerNumber": 103,
          "checkNumber": "OM314933",
          "paymentDate": "2004-12-18",
          "amount": "1676.14"
        }
      ]
    },
    {
      "customerNumber": 112,
      "customerN

<Response [200]>

In [94]:
%rest http://127.0.0.1:5000/api/classicmodels/customers?country=France

{
  "data": [
    {
      "customerNumber": 103,
      "customerName": "Atelier graphique",
      "contactLastName": "Schmitt",
      "contactFirstName": "Carine ",
      "phone": "40.32.2555",
      "addressLine1": "54, rue Royale",
      "addressLine2": null,
      "city": "Nantes",
      "state": null,
      "postalCode": "44000",
      "country": "France",
      "salesRepEmployeeNumber": 1370,
      "creditLimit": "21000.00",
      "payments": [
        {
          "customerNumber": 103,
          "checkNumber": "HQ336336",
          "paymentDate": "2004-10-19",
          "amount": "6066.78"
        },
        {
          "customerNumber": 103,
          "checkNumber": "JM555205",
          "paymentDate": "2003-06-05",
          "amount": "14571.44"
        },
        {
          "customerNumber": 103,
          "checkNumber": "OM314933",
          "paymentDate": "2004-12-18",
          "amount": "1676.14"
        }
      ]
    },
    {
      "customerNumber": 119,
      "customerN

<Response [200]>

In [95]:
%rest http://127.0.0.1:5000/api/classicmodels/customers/131/orders?status=cancelled

{
  "data": [
    {
      "orderNumber": 10248,
      "orderDate": "2004-05-07",
      "requiredDate": "2004-05-14",
      "shippedDate": null,
      "status": "Cancelled",
      "comments": "Order was mistakenly placed. The warehouse noticed the lack of documentation.",
      "customerNumber": 131,
      "orderdetails": [
        {
          "orderNumber": 10248,
          "productCode": "S10_4757",
          "quantityOrdered": 20,
          "priceEach": "126.48",
          "orderLineNumber": 3
        },
        {
          "orderNumber": 10248,
          "productCode": "S18_3029",
          "quantityOrdered": 21,
          "priceEach": "80.86",
          "orderLineNumber": 1
        },
        {
          "orderNumber": 10248,
          "productCode": "S18_3140",
          "quantityOrdered": 32,
          "priceEach": "133.86",
          "orderLineNumber": 12
        },
        {
          "orderNumber": 10248,
          "productCode": "S18_3259",
          "quantityOrdered": 42,
  

<Response [200]>

## URLs $-$ Digression

- A little more about ```mysql+pymysql://dbuser:dbuser@localhost/lahman2017```


- The connection specification above is a URL.


- "A Uniform Resource Locator (URL), colloquially termed a web address, is a reference to a web resource that specifies its location on a computer network and a mechanism for retrieving it. A URL is a specific type of Uniform Resource Identifier (URI), although many people use the two terms interchangeably. URLs occur most commonly to reference web pages (http), but are also used for file transfer (ftp), email (mailto), database access (JDBC), and many other applications." (https://en.wikipedia.org/wiki/URL)


- A URL has the format


```URI = scheme:[//authority]path[?query][#fragment]```


- The components are:
    1. Scheme: Information about the protocol, connector library, ...
    2. Authority: Usually ```userid:password```.
    3. Path: File system like folder path to the resource.
    4. We will cover query string later.
    5. Fragment: A location or subset of the resource, e.g. a section with heading.
    
    
- We have seen how we connect to MySQL from Python using ```PyMySQL``` library.

```default_cnx = pymysql.connect(host='localhost',
                             user='dbuser',
                             password='dbuser',
                             db='lahman2017',
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor)```



- Some connector libraries support a single connection string of the form:<br>
```jdbc:mysql://someuserid:somepassword@www.myurl.com:3306```


- Other databases have similar concepts, for example CouchDB.


- The REST (HTTP) URL is the same concept<br> ```http://127.0.0.1:5000/api/lahman2019clean/people?nameLast=williams&birthCity=San%20Diego```


- In this case:
    - ```HTTP``` is the protocol (Schema) instead of ```mysql+pymysql```
    - ```/api/lahman2019clear/people``` is the resource.
    - ```nameLast=williams&birthCity=San%20Diego``` is the query, and analogous to:
        - ```WHERE nameLast='williams' and birthCity='San Diego'```
        - Or the weird Donald Ferguson templates ```{"nameLast": "Williams", "birthCity": "San Diego"}```
        
        
- There is no common convention for _project_ or choosing fields. We will use the convention ```fields=x,y,z```

In [99]:
%rest http://127.0.0.1:5000/api/classicmodels/customers/131/orders?status=cancelled&fields=orderNumber,orderDate

{
  "data": [
    {
      "orderNumber": 10248,
      "orderDate": "2004-05-07",
      "orderdetails": [
        {
          "orderNumber": 10248,
          "productCode": "S10_4757",
          "quantityOrdered": 20,
          "priceEach": "126.48",
          "orderLineNumber": 3
        },
        {
          "orderNumber": 10248,
          "productCode": "S18_3029",
          "quantityOrdered": 21,
          "priceEach": "80.86",
          "orderLineNumber": 1
        },
        {
          "orderNumber": 10248,
          "productCode": "S18_3140",
          "quantityOrdered": 32,
          "priceEach": "133.86",
          "orderLineNumber": 12
        },
        {
          "orderNumber": 10248,
          "productCode": "S18_3259",
          "quantityOrdered": 42,
          "priceEach": "95.80",
          "orderLineNumber": 14
        },
        {
          "orderNumber": 10248,
          "productCode": "S18_4522",
          "quantityOrdered": 42,
          "priceEach": "87.77",
   

<Response [200]>

## Resource and Application Structure

<hr style="height:1px;">

| <img src="../../images/hw2_intro.jpeg"> |
| :---: |
| __HW2 Concept__ |

<hr style="height:1px;">

- __Note:__ The flow on the figure below is right to left.


<hr style="height:1px;">

| <img src="../../images/rest_app.jpeg"> |
| :---: |
| __REST Application__ 

<hr style="height:1px;">

## REST API and Protocol

<hr style="height:1px;">

| <img src="../../images/http_rest_protocol.jpeg" > |
| :---: |
| __HTTP and REST__ |

<hr style="height:1px;">

- The CRUD verbs are:
    - ```POST```
    - ```GET```
    - ```PUT``` (some designs use ```PATCH``` instead of ```PUT.```)
    - ```DELETE```

- The CRUD verbs occur on resources that a ```URL``` (```PATH```) identify.


- - "A Uniform Resource Locator (URL), colloquially termed a web address, is a reference to a web resource that specifies its location on a computer network and a mechanism for retrieving it. A URL is a specific type of Uniform Resource Identifier (URI), although many people use the two terms interchangeably. URLs occur most commonly to reference web pages (http), but are also used for file transfer (ftp), email (mailto), database access (JDBC), and many other applications." (https://en.wikipedia.org/wiki/URL)


- A URL has the format


```URI = scheme:[//authority]path[?query][#fragment]```


- The components are:
    1. Scheme: Information about the protocol, connector library, ...
    2. Authority: Usually ```userid:password```.
    3. Path: File system like folder path to the resource.
    4. We will cover query string later.
    5. Fragment: A location or subset of the resource, e.g. a section with heading.

- URL paths have a pattern in most applications

| Path | Mapping |
| :---: | :--- |
| /api	| The API entry point |
| /api/:coll	| A top-level collection named “coll” |
| /api/:coll/:id	| The resource “id” inside/related to collection “coll” |
| /api/:coll/:id/:subcoll	| Sub-collection “subcoll” under resource “id” |
| /api/:coll/:id/:subcoll/:subid	| The resource “subid” inside “subcoll” |


- Path examples:
    - ```/api/people/willite01```
    - ```/api/people/willite01/batting```
    - ```/api/people/willite01/batting/BOS_1960_1```
    
    
- Query string:

"On the internet, a query string is the part of a uniform resource locator (URL) which assigns values to specified parameters. The query string commonly includes fields added to a base URL by a Web browser or other client application, for example as part of an HTML form.

A web server can handle a Hypertext Transfer Protocol request either by reading a file from its file system based on the URL path or by handling the request using logic that is specific to the type of resource. In cases where special logic is invoked, the query string will be available to that logic for use in its processing, along with the path component of the URL." (https://en.wikipedia.org/wiki/Query_string)


- Query string example:
    - ```http://127.0.0.1/api/people?nameLast=Williams&nameFirst=Ted
    - maps to
    - ```SELECT * FROM people where nameLast='Williams' and nameFirst='Ted'```
    
    
- There is no standard way to specify _project._ A common convent is ```fields=f1,f2,...```


- Full example:
    - ```http://127.0.0.1/api/people?nameLast=Williams&nameFirst=Ted&fields=playerID,nameLast,nameFirst,throws, bats``` 
    - maps to
    - ```SELECT playerID,nameLast,nameFirst,throws,bats FROM people where nameLast='Williams' and nameFirst='Ted'```
    
    
- These are very common conventions, which we will use for HW2. Applications and frameworks also use other conventions.

__Examples__

- ```GET /api/people/willite01&fields=playerID,nameLast,nameFirst,bats,throws``` would return

```
{
    "data": {
        "playerID": {
            "value": "willite01",
            "link": {
                "rel": "people",
                "href": "/api/people/willite01"
            }
        },
        "nameLast": "Williams",
        "nameFirst": "Ted",
        "bats": "L",
        "throws": "R",
    }
    "links": {
        "appearances": { "href": "/api/people/willite01/appearances", "rel": "Appearances" },
        "batting": { "href": "/api/people/willite01/batting", "rel": "Batting" },
        "self": { "href": "/api/people/willite01", "rel": "Self" },
        
    }
}```


- ```GET /api/people/nameLast=Williams&fields=playerID,nameLast,nameFirst``` would return

```
"data": [
            {
                data: {
                    "playerID": {
                    "value": "williac01",
                    "link": {
                        "rel": "people",
                        "href": "/api/people/williac01"
                    },
                    "nameFirst": "Ace",
                    "nameLast": "Williams"
                },
                "links": {
                    "appearances": { "href": "/api/people/williac01/appearances", "rel": "Appearances" },
                    "batting": { "href": "/api/people/williac01/batting", "rel": "Batting" },
                    "self": { "href": "/api/people/williac01", "rel": "Self" }
                }
            },
            {
                data: {
                    "playerID": {
                    "value": "willial02",
                    "link": {
                        "rel": "people",
                        "href": "/api/people/willial02"
                    },
                    "nameFirst": "Al",
                    "nameLast": "Williams"
                },
                "links": {
                    "appearances": { "href": "/api/people/willial02/appearances", "rel": "Appearances" },
                    "batting": { "href": "/api/people/willial02/batting", "rel": "Batting" },
                    "self": { "href": "/api/people/willial02", "rel": "Self" }
                }
                    
            }
        ],
    "links": {
        "next": { "href": "/api/people/nameLast=Williams&fields=playerID,nameLast,nameFirst&limit=2&offset=2,
            "rel": "next"},
        "self": { "href": "/api/people/nameLast=Williams&fields=playerID,nameLast,nameFirst&limit=0&offset=2,
            "current": "next"}
    }
}
```


- ```limit``` and ```offset``` implement _pagination._

"Currently, when an HTTP GET request is issued on ... route, all of the table's rows are returned. This may not be a big deal with only 107 rows in ... table, but imagine what would happen if the table contained thousands or millions of rows. Clients such as mobile and web apps generally consume and display only a fraction of the rows available in the database and then fetch more rows when needed — perhaps when a user scrolls down or clicks the "next" button on some pagination control in the UI.

To allow for this, REST APIs need to support a means of paginating the results returned. Once pagination is supported, sorting capabilities become important as data usually needs to be sorted prior to pagination being applied. Additionally, a means of filtering data is very important for performance. Why send data from the database, through the mid-tier, and all the way to the client if it's not needed?" (https://dzone.com/articles/creating-a-rest-api-manual-pagination-sorting-and)


- You have seen that I have to do pagination when submitting queries to MySQL from Jupyter notebooks. If I do not use ```LIMIT,``` the amount of returned data causes the Jupyter notebook/browser to freeze/lock-up.

# Homework 2: REST and Linked Data

- Homework 2 is to build an application that surfaces a linked data, REST API on top of a relational database.


- It will implement a set of core functions:
    - Basic operations: GET, PUT, DELETE, POST mapped onto SQL
    - Query strings and field selection.
    - Individual resource identification using primary keys.
    - Path following using foreign keys.
    - ... ...
    
    
- Typically, HW 3 has been the "homework from heck." Last semester, I went a little crazy and HW 2 was brutal. I am going to work with the TAs to define a much reduced scope and clearer requirements.